RobotEvolver: GL_DialogWindow Class Reference
GL_DialogWindow Class Reference
Very basic OpenGL Graphical Userinterface Window with text, toggle, slider control.
#include <GL_DialogWindow.h>
Public Member Functions
GL_DialogWindow (int horPos, int vertPos, int dialogWidth, int dialogHeight, btCollisionObject *colObject, const char *dialogTitle)
virtual ~GL_DialogWindow ()
void draw (btScalar deltaTime)
void setScreenSize (int width, int height)
void setStartPosition (int dialogHorPos, int dialogVertPos)
void addControl (GL_DialogControl *control)
void removeControl (GL_DialogControl *control)
btCollisionObject * getCollisionObject ()
int getDialogHorPos () const
int getDialogVertPos () const
int getDialogWidth () const
int getDialogHeight () const
int getScreenWidth () const
int getScreenHeight () const
int getNumControls () const
const GL_DialogControl * getControl (int index) const
GL_DialogControl * getControl (int index)
Protected Member Functions
void saveOpenGLState ()
void restoreOpenGLState ()
Private Attributes
int m_dialogHorPos
int m_dialogVertPos
int m_dialogWidth
int m_dialogHeight
int m_screenWidth
int m_screenHeight
const char * m_dialogTitle
GLfloat m_PrevLineWidth
GLint m_PrevTexEnv
GLint m_PrevPolygonMode [2]
GLint m_MaxClipPlanes
GLint m_PrevTexture
GLint m_PrevArrayBufferARB
GLint m_PrevElementArrayBufferARB
GLboolean m_PrevVertexProgramARB
GLboolean m_PrevFragmentProgramARB
GLuint m_PrevProgramObjectARB
GLboolean m_PrevTexture3D
GLboolean m_PrevActiveTexture1D [32]
GLboolean m_PrevActiveTexture2D [32]
GLboolean m_PrevActiveTexture3D [32]
GLint m_PrevActiveTextureARB
bool m_SupportTexRect
GLboolean m_PrevTexRectARB
GLint m_PrevBlendEquation
GLint m_PrevBlendEquationRGB
GLint m_PrevBlendEquationAlpha
GLint m_PrevBlendSrcRGB
GLint m_PrevBlendDstRGB
GLint m_PrevBlendSrcAlpha
GLint m_PrevBlendDstAlpha
GLint m_ViewportInit [4]
GLfloat m_ProjMatrixInit [16]
btCollisionObject * m_collisionObject
btAlignedObjectArray
< GL_DialogControl * > m_controls
Detailed Description
Very basic OpenGL Graphical Userinterface Window with text, toggle, slider control.
Definition at line 162 of file GL_DialogWindow.h.
Constructor & Destructor Documentation
GL_DialogWindow::GL_DialogWindow (int horPos, int vertPos, int dialogWidth, int dialogHeight, btCollisionObject * colObject, const char * dialogTitle)
Definition at line 28 of file GL_DialogWindow.cpp.
 :m_dialogHorPos(horPos),
 m_dialogVertPos(vertPos),
 m_dialogWidth(dialogWidth),
 m_dialogHeight(dialogHeight),
 m_screenWidth(0),
 m_screenHeight(0),
 m_dialogTitle(dialogTitle),
 m_MaxClipPlanes(-1),
 m_collisionObject(collisionObject)
 {
 }
GL_DialogWindow::~GL_DialogWindow () virtual
Definition at line 47 of file GL_DialogWindow.cpp.
 {
 }
Member Function Documentation
void GL_DialogWindow::addControl (GL_DialogControl * control) inline
Definition at line 229 of file GL_DialogWindow.h.
Referenced by GL_DialogDynamicsWorld::createSlider(), and GL_DialogDynamicsWorld::createToggle().
     {
         m_controls.push_back(control);
     }
void GL_DialogWindow::draw (btScalar deltaTime)
Definition at line 134 of file GL_DialogWindow.cpp.
 {
     if (!m_screenWidth || !m_screenHeight)
         return;
     m_dialogHorPos = int(m_collisionObject->getWorldTransform().getOrigin()[0]+m_screenWidth/2.f-m_dialogWidth/2.f);
     m_dialogVertPos = int(m_collisionObject->getWorldTransform().getOrigin()[1]+m_screenHeight/2.f-m_dialogHeight/2.f);
     saveOpenGLState();
     //drawRect(m_dialogHorPos,m_dialogVertPos,m_dialogHorPos+m_dialogWidth,m_dialogVertPos+m_dialogHeight,0xa6000000);
     unsigned int argbColor = 0x86000000;
     int charHeight = 16;
     int charWidth = 10;
     int titleHeight = charHeight + 2;
     drawRect(m_dialogHorPos,m_dialogVertPos,m_dialogHorPos+m_dialogWidth-1,m_dialogVertPos+titleHeight,argbColor,argbColor,argbColor,argbColor);
     //const unsigned int COL0 = 0x50ffffff;
     const unsigned int COL0 = 0xffffffff;
     const unsigned int COL1 = 0xff1f1f1f;
     drawRect(m_dialogHorPos,m_dialogVertPos,m_dialogHorPos+m_dialogWidth-1,m_dialogVertPos+1,COL0,COL0,COL1,COL1);
     argbColor = 0x864f4f4f;
     drawRect(m_dialogHorPos+1,m_dialogVertPos+titleHeight,m_dialogHorPos+m_dialogWidth-1,m_dialogVertPos+m_dialogHeight,argbColor,argbColor,argbColor,argbColor);
     int y = m_dialogVertPos+charHeight+1;
     glLineWidth(3);
     drawLine(m_dialogHorPos, y, m_dialogHorPos+m_dialogWidth-1, y, 0x80afafaf,0x80afafaf);
     unsigned int  clight = 0x5FFFFFFF; // bar contour
     drawLine(m_dialogHorPos, m_dialogVertPos, m_dialogHorPos, m_dialogVertPos+m_dialogHeight, clight,clight);
     drawLine(m_dialogHorPos, m_dialogVertPos, m_dialogHorPos+m_dialogWidth, m_dialogVertPos, clight,clight);
     drawLine(m_dialogHorPos+m_dialogWidth, m_dialogVertPos, m_dialogHorPos+m_dialogWidth, m_dialogVertPos+m_dialogHeight, clight,clight);
     drawLine(m_dialogHorPos, m_dialogVertPos+m_dialogHeight, m_dialogHorPos+m_dialogWidth, m_dialogVertPos+m_dialogHeight, clight,clight);
     int dshad = 3;  // bar shadows
     unsigned int  cshad = (((0x40000000>>24)/2)<<24) & 0xFF000000;
     drawRect(m_dialogHorPos, m_dialogVertPos+m_dialogHeight, m_dialogHorPos+dshad, m_dialogVertPos+m_dialogHeight+dshad, 0, cshad, 0, 0);
     drawRect(m_dialogHorPos+dshad+1, m_dialogVertPos+m_dialogHeight, m_dialogHorPos+m_dialogWidth-1, m_dialogVertPos+m_dialogHeight+dshad, cshad, cshad, 0, 0);
     drawRect(m_dialogHorPos+m_dialogWidth, m_dialogVertPos+m_dialogHeight, m_dialogHorPos+m_dialogWidth+dshad, m_dialogVertPos+m_dialogHeight+dshad, cshad, 0, 0, 0);
     drawRect(m_dialogHorPos+m_dialogWidth, m_dialogVertPos, m_dialogHorPos+m_dialogWidth+dshad, m_dialogVertPos+dshad, 0, 0, cshad, 0);
     drawRect(m_dialogHorPos+m_dialogWidth, m_dialogVertPos+dshad+1, m_dialogHorPos+m_dialogWidth+dshad, m_dialogVertPos+m_dialogHeight-1, cshad, 0, cshad, 0);
     int yInc = 16;
     int curHorPos = m_dialogHorPos+5;
     int curVertPos = m_dialogVertPos;
     curVertPos += yInc;
     GLDebugDrawString(m_dialogHorPos+m_dialogWidth/2-((int(strlen(m_dialogTitle)/2))*charWidth),m_dialogVertPos+yInc ,m_dialogTitle);
     curVertPos += 20;
     for (int i=0;i<m_controls.size();i++)
     {
         m_controls[i]->draw(curHorPos,curVertPos,deltaTime);
     }
     restoreOpenGLState();
 }
btCollisionObject* GL_DialogWindow::getCollisionObject () inline
Definition at line 239 of file GL_DialogWindow.h.
Referenced by GL_DialogDynamicsWorld::createSlider(), and GL_DialogDynamicsWorld::createToggle().
     {
         return m_collisionObject;
     }
const GL_DialogControl* GL_DialogWindow::getControl (int index) const inline
Definition at line 275 of file GL_DialogWindow.h.
     {
         return m_controls[index];
     }
GL_DialogControl* GL_DialogWindow::getControl (int index) inline
Definition at line 279 of file GL_DialogWindow.h.
     {
         return m_controls[index];
     }
int GL_DialogWindow::getDialogHeight () const inline
Definition at line 257 of file GL_DialogWindow.h.
Referenced by GL_DialogDynamicsWorld::createSlider(), and GL_DialogDynamicsWorld::createToggle().
     {
         return m_dialogHeight;
     }
int GL_DialogWindow::getDialogHorPos () const inline
Definition at line 244 of file GL_DialogWindow.h.
Referenced by GL_DialogDynamicsWorld::createSlider(), and GL_DialogDynamicsWorld::createToggle().
     {
         return m_dialogHorPos;
     }
int GL_DialogWindow::getDialogVertPos () const inline
Definition at line 248 of file GL_DialogWindow.h.
Referenced by GL_DialogDynamicsWorld::createSlider(), and GL_DialogDynamicsWorld::createToggle().
     {
         return m_dialogVertPos;
     }
int GL_DialogWindow::getDialogWidth () const inline
Definition at line 252 of file GL_DialogWindow.h.
Referenced by GL_DialogDynamicsWorld::createSlider(), GL_DialogDynamicsWorld::createToggle(), and GL_SliderControl::draw().
     {
         return m_dialogWidth;
     }
int GL_DialogWindow::getNumControls () const inline
Definition at line 270 of file GL_DialogWindow.h.
Referenced by GL_DialogDynamicsWorld::createSlider(), and GL_DialogDynamicsWorld::createToggle().
     {
         return m_controls.size();
     }
int GL_DialogWindow::getScreenHeight () const inline
Definition at line 265 of file GL_DialogWindow.h.
Referenced by GL_ToggleControl::draw(), and GL_SliderControl::draw().
     {
         return m_screenHeight;
     }
int GL_DialogWindow::getScreenWidth () const inline
Definition at line 261 of file GL_DialogWindow.h.
Referenced by GL_ToggleControl::draw(), and GL_SliderControl::draw().
     {
         return m_screenWidth;
     }
void GL_DialogWindow::removeControl (GL_DialogControl * control) inline
Definition at line 234 of file GL_DialogWindow.h.
     {
         m_controls.remove(control);
     }
void GL_DialogWindow::restoreOpenGLState () protected
Definition at line 249 of file GL_DialogWindow.cpp.
Referenced by draw().
 {
     glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, m_PrevTexEnv);
     glLineWidth(m_PrevLineWidth);
     glMatrixMode(GL_PROJECTION);
     glPopMatrix();
     glMatrixMode(GL_MODELVIEW);
     glPopMatrix();
     glMatrixMode(GL_TEXTURE);
     glPopMatrix();
     glPopClientAttrib();
     glPopAttrib();
 }
void GL_DialogWindow::saveOpenGLState () protected
Definition at line 200 of file GL_DialogWindow.cpp.
Referenced by draw().
 {
 #if 0
     glPushAttrib(GL_ALL_ATTRIB_BITS);
     glPushClientAttrib(GL_CLIENT_ALL_ATTRIB_BITS);
 #endif
     glMatrixMode(GL_TEXTURE);
     glPushMatrix();
     glLoadIdentity();
     glMatrixMode(GL_MODELVIEW);
     glPushMatrix();
     glLoadIdentity();
     glMatrixMode(GL_PROJECTION);
     glPushMatrix();
     GLint Vp[4];
     glGetIntegerv(GL_VIEWPORT, Vp);
     if( m_screenWidth>0 && m_screenHeight>0 )
     {
         Vp[0] = 0;
         Vp[1] = 0;
         Vp[2] = m_screenWidth-1;
         Vp[3] = m_screenHeight-1;
         glViewport(Vp[0], Vp[1], Vp[2], Vp[3]);
     }
     glLoadIdentity();
     glOrtho(Vp[0], Vp[0]+Vp[2], Vp[1]+Vp[3], Vp[1], -1, 1);
     glGetIntegerv(GL_VIEWPORT, m_ViewportInit);
     glGetFloatv(GL_PROJECTION_MATRIX, m_ProjMatrixInit);
     glGetFloatv(GL_LINE_WIDTH, &m_PrevLineWidth);
  //   glDisable(GL_POLYGON_STIPPLE);
     glLineWidth(1);
     glDisable(GL_LINE_SMOOTH);
 //    glDisable(GL_LINE_STIPPLE);
     glDisable(GL_CULL_FACE);
     glDisable(GL_DEPTH_TEST);
     glDisable(GL_LIGHTING);
     glEnable(GL_BLEND);
     glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
     glGetTexEnviv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, &m_PrevTexEnv);
     glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);
     glDisable(GL_TEXTURE_2D);
 }
void GL_DialogWindow::setScreenSize (int width, int height)
Definition at line 42 of file GL_DialogWindow.cpp.
 {
     m_screenWidth = width;
     m_screenHeight = height;
 }
void GL_DialogWindow::setStartPosition (int dialogHorPos, int dialogVertPos)
Field Documentation
btCollisionObject* GL_DialogWindow::m_collisionObject private
Definition at line 203 of file GL_DialogWindow.h.
Referenced by draw(), and getCollisionObject().
btAlignedObjectArray<GL_DialogControl*> GL_DialogWindow::m_controls private
Definition at line 205 of file GL_DialogWindow.h.
Referenced by addControl(), draw(), getControl(), getNumControls(), and removeControl().
int GL_DialogWindow::m_dialogHeight private
Definition at line 168 of file GL_DialogWindow.h.
Referenced by draw(), and getDialogHeight().
int GL_DialogWindow::m_dialogHorPos private
Definition at line 165 of file GL_DialogWindow.h.
Referenced by draw(), and getDialogHorPos().
const char* GL_DialogWindow::m_dialogTitle private
Definition at line 173 of file GL_DialogWindow.h.
Referenced by draw().
int GL_DialogWindow::m_dialogVertPos private
Definition at line 166 of file GL_DialogWindow.h.
Referenced by draw(), and getDialogVertPos().
int GL_DialogWindow::m_dialogWidth private
Definition at line 167 of file GL_DialogWindow.h.
Referenced by draw(), and getDialogWidth().
GLint GL_DialogWindow::m_MaxClipPlanes private
Definition at line 179 of file GL_DialogWindow.h.
GLboolean GL_DialogWindow::m_PrevActiveTexture1D[32] private
Definition at line 187 of file GL_DialogWindow.h.
GLboolean GL_DialogWindow::m_PrevActiveTexture2D[32] private
Definition at line 188 of file GL_DialogWindow.h.
GLboolean GL_DialogWindow::m_PrevActiveTexture3D[32] private
Definition at line 189 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_PrevActiveTextureARB private
Definition at line 190 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_PrevArrayBufferARB private
Definition at line 181 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_PrevBlendDstAlpha private
Definition at line 199 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_PrevBlendDstRGB private
Definition at line 197 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_PrevBlendEquation private
Definition at line 193 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_PrevBlendEquationAlpha private
Definition at line 195 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_PrevBlendEquationRGB private
Definition at line 194 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_PrevBlendSrcAlpha private
Definition at line 198 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_PrevBlendSrcRGB private
Definition at line 196 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_PrevElementArrayBufferARB private
Definition at line 182 of file GL_DialogWindow.h.
GLboolean GL_DialogWindow::m_PrevFragmentProgramARB private
Definition at line 184 of file GL_DialogWindow.h.
GLfloat GL_DialogWindow::m_PrevLineWidth private
Definition at line 176 of file GL_DialogWindow.h.
Referenced by restoreOpenGLState(), and saveOpenGLState().
GLint GL_DialogWindow::m_PrevPolygonMode[2] private
Definition at line 178 of file GL_DialogWindow.h.
GLuint GL_DialogWindow::m_PrevProgramObjectARB private
Definition at line 185 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_PrevTexEnv private
Definition at line 177 of file GL_DialogWindow.h.
Referenced by restoreOpenGLState(), and saveOpenGLState().
GLboolean GL_DialogWindow::m_PrevTexRectARB private
Definition at line 192 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_PrevTexture private
Definition at line 180 of file GL_DialogWindow.h.
GLboolean GL_DialogWindow::m_PrevTexture3D private
Definition at line 186 of file GL_DialogWindow.h.
GLboolean GL_DialogWindow::m_PrevVertexProgramARB private
Definition at line 183 of file GL_DialogWindow.h.
GLfloat GL_DialogWindow::m_ProjMatrixInit[16] private
Definition at line 201 of file GL_DialogWindow.h.
Referenced by saveOpenGLState().
int GL_DialogWindow::m_screenHeight private
Definition at line 171 of file GL_DialogWindow.h.
Referenced by draw(), getScreenHeight(), saveOpenGLState(), and setScreenSize().
int GL_DialogWindow::m_screenWidth private
Definition at line 170 of file GL_DialogWindow.h.
Referenced by draw(), getScreenWidth(), saveOpenGLState(), and setScreenSize().
bool GL_DialogWindow::m_SupportTexRect private
Definition at line 191 of file GL_DialogWindow.h.
GLint GL_DialogWindow::m_ViewportInit[4] private
Definition at line 200 of file GL_DialogWindow.h.
Referenced by saveOpenGLState().
The documentation for this class was generated from the following files:
GL_DialogWindow.h
GL_DialogWindow.cpp