RobotEvolver: GLDebugFont.h File Reference
GLDebugFont.h File Reference
#include "LinearMath/btVector3.h"
Functions
void GLDebugDrawStringInternal (int x, int y, const char *string, const btVector3 &rgb, bool enableBlend, int spacing)
void GLDebugDrawStringInternal (int x, int y, const char *string, const btVector3 &rgb)
void GLDebugDrawString (int x, int y, const char *string)
void GLDebugResetFont (int screenWidth, int screenHeight)
Function Documentation
void GLDebugDrawString (int x, int y, const char * string)
Definition at line 222 of file GLDebugFont.cpp.
Referenced by DemoApplication::displayProfileString(), GL_TextControl::draw(), GL_DialogWindow::draw(), SoftDemo::renderme(), and DemoApplication::renderme().
 {
     btVector3 rgb(1,1,1);
     GLDebugDrawStringInternal(x,y,string,rgb);
 }
void GLDebugDrawStringInternal (int x, int y, const char * string, const btVector3 & rgb, bool enableBlend, int spacing)
Definition at line 89 of file GLDebugFont.cpp.
 {
     if (!sTexturesInitialized)
     {
         GLDebugResetFont(sScreenWidth,sScreenHeight);
     }
     if (strlen(string))
     {
         glColor4f(rgb.getX(),rgb.getY(),rgb.getZ(),1.f);
         float   cx;
         float   cy;
         glMatrixMode(GL_TEXTURE);
         glLoadIdentity();
         glDisable(GL_TEXTURE_GEN_S);
         glDisable(GL_TEXTURE_GEN_T);
         glDisable(GL_TEXTURE_GEN_R);
         glEnable(GL_TEXTURE_2D);
         glBlendFunc(GL_SRC_ALPHA,GL_ONE);
         glDepthFunc (GL_LEQUAL);
         if (enableBlend)
         {
             glEnable(GL_BLEND);
         } else
         {
             glDisable(GL_BLEND);
         }
         glEnable (GL_DEPTH_TEST);
         glBindTexture(GL_TEXTURE_2D, sTexture);
         glDisable(GL_DEPTH_TEST);
         glMatrixMode(GL_PROJECTION);
         glPushMatrix();
         glLoadIdentity();
         glOrtho(0,sScreenWidth,0,sScreenHeight,-1,1);
         glMatrixMode(GL_MODELVIEW);
         glPushMatrix();
         glLoadIdentity();
         glTranslatef(btScalar(x),btScalar(sScreenHeight - y),btScalar(0));
 #if USE_ARRAYS
         glDisableClientState(GL_COLOR_ARRAY);
         glDisableClientState(GL_NORMAL_ARRAY);
         glEnableClientState(GL_VERTEX_ARRAY);
         glEnableClientState (GL_TEXTURE_COORD_ARRAY);
 #endif
         GLfloat verts[] ={
             0.0f, 1.0f, 0.0f,
             -1.0f, -1.0f, 0.0f,
             1.0f, -1.0f, 0.0f,
             0.f,0.f,0.f
         };
         GLfloat uv_texcoords[] = {
             0,0,
             0,0,
             0,0,
             0,0
         };
         verts[0] = 0;       verts[1] = 0;       verts[2] = 0;
         verts[3] = 16-1;    verts[4] = 0;       verts[5] = 0;
         verts[6] = 16-1;    verts[7] = 16-1;    verts[8] = 0;
         verts[9] = 0;       verts[10] = 16-1;   verts[11] = 0;
         for (int i=0;i<int (strlen(string));i++)
         {
             char ch = string[i]-32;
             if (ch>=0)
             {
                 cx=float(ch%16) * btScalar(1./16.f);
                 cy=float(ch/16) * btScalar(1./16.f);
                 uv_texcoords[0] = cx;           uv_texcoords[1] = btScalar(1-cy-1./16.f);
                 uv_texcoords[2] = btScalar(cx+1./16.f); uv_texcoords[3] = btScalar(1-cy-1./16.f);
                 uv_texcoords[4] = btScalar(cx+1./16.f); uv_texcoords[5] = btScalar(1-cy);
                 uv_texcoords[6] = cx;           uv_texcoords[7] = btScalar(1-cy);
 #if USE_ARRAYS
                 glTexCoordPointer(2,GL_FLOAT,0,uv_texcoords);
                 glVertexPointer(3, GL_FLOAT, 0, verts);
                 glDrawArrays(GL_TRIANGLE_FAN, 0, 4);
 #else
                 glBegin(GL_QUADS);
                 glTexCoord2f(cx,1-cy-1./16.f);
                 glVertex2i(0,0);
                 glTexCoord2f(cx+1./16.f,1-cy-1./16.f);
                 glVertex2i(16 - 1,0);
                 glTexCoord2f(cx+1./16.f,1-cy);
                 glVertex2i(16 - 1,16 -1);
                 glTexCoord2f(cx,1-cy);
                 glVertex2i(0,16 -1);
                 glEnd();
 #endif
                 glTranslatef(spacing,0,0);
             }
         }
         glMatrixMode(GL_PROJECTION);
         glPopMatrix();
         glMatrixMode(GL_MODELVIEW);
         glPopMatrix();
 #if 1
         glEnable(GL_DEPTH_TEST);
         glBlendFunc(GL_SRC_ALPHA,GL_ONE);
         glDepthFunc (GL_LEQUAL);
         glDisable(GL_BLEND);
         glDisable(GL_TEXTURE_2D);
         glMatrixMode(GL_TEXTURE);
         glLoadIdentity();
         glScalef(btScalar(0.025),btScalar(0.025),btScalar(0.025));
 #endif
         glMatrixMode(GL_MODELVIEW);
 #if USE_ARRAYS
         glDisableClientState(GL_VERTEX_ARRAY);
         glDisableClientState (GL_TEXTURE_COORD_ARRAY);
 #endif
         //glDisable(GL_TEXTURE_2D);
     }
 }
void GLDebugDrawStringInternal (int x, int y, const char * string, const btVector3 & rgb)
Definition at line 84 of file GLDebugFont.cpp.
Referenced by GL_ToggleControl::draw(), GL_SliderControl::draw(), GLDebugDrawString(), and GLDebugDrawStringInternal().
 {
     GLDebugDrawStringInternal(x,y,string,rgb,true,10);
 }
void GLDebugResetFont (int screenWidth, int screenHeight)
Definition at line 59 of file GLDebugFont.cpp.
Referenced by GLDebugDrawStringInternal(), and DemoApplication::reshape().
 {
     if ((sScreenWidth == screenWidth) && (sScreenHeight == screenHeight))
         return;
     sScreenWidth = screenWidth;
     sScreenHeight = screenHeight;
     if (!sTexturesInitialized)
     {
         sTexturesInitialized = true;
         glGenTextures(1, &sTexture);
         glBindTexture(GL_TEXTURE_2D, sTexture);
         glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR);
         glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR);
         glTexImage2D(GL_TEXTURE_2D, 0, 3, 256 , 256 , 0, GL_RGB, GL_UNSIGNED_BYTE, &sFontData[0]);
     }
 //  printf("generating font at resolution %d,%d\n",screenWidth,screenHeight);
 }