RobotEvolver: SoftDemo.cpp File Reference
SoftDemo.cpp File Reference
#include "btBulletDynamicsCommon.h"
#include "BulletSoftBody/btSoftRigidDynamicsWorld.h"
#include "BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h"
#include "BulletCollision/NarrowPhaseCollision/btGjkEpa2.h"
#include "LinearMath/btQuickprof.h"
#include "LinearMath/btIDebugDraw.h"
#include "Meshes/BunnyMesh.h"
#include "Meshes/TorusMesh.h"
#include <stdio.h>
#include "LinearMath/btConvexHull.h"
#include "BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.h"
#include "BulletSoftBody/btSoftBodyHelpers.h"
#include "SoftDemo.h"
#include "BulletDemoFiles/GL_ShapeDrawer.h"
#include "BulletDemoFiles/GLDebugFont.h"
#include "BulletDemoFiles/GlutStuff.h"
#include "Meshes/bunny.inl"
#include "Meshes/cube.inl"
Data Structures
struct ImplicitSphere
struct TetraBunny
struct TetraCube
struct MotorControl
struct SteerControl
Macros
#define DEMO_MODE_TIMEOUT 15.f
#define CUBE_HALF_EXTENTS 1.5
#define EXTRA_HEIGHT -10.f
#define SQ(_x_) (_x_)*(_x_)
Functions
void pickingPreTickCallback (btDynamicsWorld *world, btScalar timeStep)
for mouse picking
static btScalar UnitRand ()
static btScalar SignedUnitRand ()
static btVector3 Vector3Rand ()
static void Ctor_RbUpStack (SoftDemo *pdemo, int count)
static void Ctor_BigBall (SoftDemo *pdemo, btScalar mass=10)
static btRigidBody * Ctor_BigPlate (SoftDemo *pdemo, btScalar mass=15, btScalar height=4)
static void Ctor_LinearStair (SoftDemo *pdemo, const btVector3 &org, const btVector3 &sizes, btScalar angle, int count)
static btSoftBody * Ctor_SoftBox (SoftDemo *pdemo, const btVector3 &p, const btVector3 &s)
static btSoftBody * Ctor_SoftBoulder (SoftDemo *pdemo, const btVector3 &p, const btVector3 &s, int np, int id)
static void Init_Ropes (SoftDemo *pdemo)
static void Init_RopeAttach (SoftDemo *pdemo)
static void Init_ClothAttach (SoftDemo *pdemo)
static void Init_Impact (SoftDemo *pdemo)
static void Init_CapsuleCollision (SoftDemo *pdemo)
static void Init_Collide (SoftDemo *pdemo)
static void Init_Collide2 (SoftDemo *pdemo)
static void Init_Collide3 (SoftDemo *pdemo)
static void Init_Aero (SoftDemo *pdemo)
static void Init_Aero2 (SoftDemo *pdemo)
static void Init_Friction (SoftDemo *pdemo)
static void Init_Pressure (SoftDemo *pdemo)
static void Init_Volume (SoftDemo *pdemo)
static void Init_Sticks (SoftDemo *pdemo)
static void Init_Bending (SoftDemo *pdemo)
static void Init_Cloth (SoftDemo *pdemo)
static void Init_Bunny (SoftDemo *pdemo)
static void Init_BunnyMatch (SoftDemo *pdemo)
static void Init_Torus (SoftDemo *pdemo)
static void Init_TorusMatch (SoftDemo *pdemo)
static void Init_Cutting1 (SoftDemo *pdemo)
static void Ctor_Gear (SoftDemo *pdemo, const btVector3 &pos, btScalar speed)
static btSoftBody * Ctor_ClusterBunny (SoftDemo *pdemo, const btVector3 &x, const btVector3 &a)
static btSoftBody * Ctor_ClusterTorus (SoftDemo *pdemo, const btVector3 &x, const btVector3 &a, const btVector3 &s=btVector3(2, 2, 2))
static void Init_ClusterDeform (SoftDemo *pdemo)
static void Init_ClusterCollide1 (SoftDemo *pdemo)
static void Init_ClusterCollide2 (SoftDemo *pdemo)
static void Init_ClusterSocket (SoftDemo *pdemo)
static void Init_ClusterHinge (SoftDemo *pdemo)
static void Init_ClusterCombine (SoftDemo *pdemo)
static void Init_ClusterCar (SoftDemo *pdemo)
static void Init_ClusterRobot (SoftDemo *pdemo)
static void Init_ClusterStackSoft (SoftDemo *pdemo)
static void Init_ClusterStackMixed (SoftDemo *pdemo)
static void Init_TetraBunny (SoftDemo *pdemo)
static void Init_TetraCube (SoftDemo *pdemo)
Variables
float eye [3]
btSoftBody implementation by Nathanael Presson
int glutScreenWidth
int glutScreenHeight
static bool sDemoMode = false
const int maxProxies = 32766
const int maxOverlap = 65535
static btVector3 * gGroundVertices =0
static int * gGroundIndices =0
static btBvhTriangleMeshShape * trimeshShape =0
static btRigidBody * staticBody = 0
static float waveheight = 5.f
const float TRIANGLE_SIZE =8.f
int current_demo =20
const int gNumObjects = 1
const int maxNumObjects = 32760
int gNumManifold
int gOverlappingPairs
MotorControl motorcontrol
static SteerControl steercontrol_f (+1)
static SteerControl steercontrol_r (-1)
void(* demofncs [])(SoftDemo *)
Macro Definition Documentation
#define CUBE_HALF_EXTENTS 1.5
Definition at line 67 of file SoftDemo.cpp.
Referenced by SoftDemo::initPhysics().
#define DEMO_MODE_TIMEOUT 15.f
Definition at line 56 of file SoftDemo.cpp.
Referenced by SoftDemo::clientMoveAndDisplay().
#define EXTRA_HEIGHT -10.f
Definition at line 68 of file SoftDemo.cpp.
#define SQ (_x_) (_x_)*(_x_)
Referenced by SoftDemo::mouseMotionFunc().
Function Documentation
static void Ctor_BigBall (SoftDemo * pdemo, btScalar mass = 10) static
Definition at line 388 of file SoftDemo.cpp.
Referenced by Init_Sticks().
 {
     btTransform startTransform;
     startTransform.setIdentity();
     startTransform.setOrigin(btVector3(0,13,0));
     pdemo->localCreateRigidBody(mass,startTransform,new btSphereShape(3));
 }
static btRigidBody* Ctor_BigPlate (SoftDemo * pdemo, btScalar mass = 15, btScalar height = 4) static
Definition at line 399 of file SoftDemo.cpp.
Referenced by Init_ClusterHinge(), Init_ClusterSocket(), Init_ClusterStackMixed(), Init_Pressure(), and Init_Volume().
 {
     btTransform startTransform;
     startTransform.setIdentity();
     startTransform.setOrigin(btVector3(0,height,0.5));
     btRigidBody*        body=pdemo->localCreateRigidBody(mass,startTransform,new btBoxShape(btVector3(5,1,5)));
     body->setFriction(1);
     return(body);
 }
static btSoftBody* Ctor_ClusterBunny (SoftDemo * pdemo, const btVector3 & x, const btVector3 & a) static
Definition at line 1081 of file SoftDemo.cpp.
Referenced by Init_ClusterCar().
 {
     btSoftBody* psb=btSoftBodyHelpers::CreateFromTriMesh(pdemo->m_softBodyWorldInfo,gVerticesBunny,&gIndicesBunny[0][0],BUNNY_NUM_TRIANGLES);
     btSoftBody::Material*   pm=psb->appendMaterial();
     pm->m_kLST              =   1;
     pm->m_flags             -=  btSoftBody::fMaterial::DebugDraw;
     psb->generateBendingConstraints(2,pm);
     psb->m_cfg.piterations  =   2;
     psb->m_cfg.kDF          =   1;
     psb->m_cfg.collisions   =   btSoftBody::fCollision::CL_SS+
         btSoftBody::fCollision::CL_RS;
     psb->randomizeConstraints();
     btMatrix3x3 m;
     m.setEulerZYX(a.x(),a.y(),a.z());
     psb->transform(btTransform(m,x));
     psb->scale(btVector3(8,8,8));
     psb->setTotalMass(150,true);
     psb->generateClusters(1);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     return(psb);
 }
static btSoftBody* Ctor_ClusterTorus (SoftDemo * pdemo, const btVector3 & x, const btVector3 & a, const btVector3 & s = btVector3(2,2,2)) static
Definition at line 1104 of file SoftDemo.cpp.
Referenced by Init_ClusterCar(), Init_ClusterCombine(), Init_ClusterDeform(), Init_ClusterHinge(), Init_ClusterSocket(), Init_ClusterStackMixed(), and Init_ClusterStackSoft().
 {
     btSoftBody* psb=btSoftBodyHelpers::CreateFromTriMesh(pdemo->m_softBodyWorldInfo,gVertices,&gIndices[0][0],NUM_TRIANGLES);
     btSoftBody::Material*   pm=psb->appendMaterial();
     pm->m_kLST              =   1;
     pm->m_flags             -=  btSoftBody::fMaterial::DebugDraw;
     psb->generateBendingConstraints(2,pm);
     psb->m_cfg.piterations  =   2;
     psb->m_cfg.collisions   =   btSoftBody::fCollision::CL_SS+
         btSoftBody::fCollision::CL_RS;
     psb->randomizeConstraints();
     psb->scale(s);
     psb->rotate(btQuaternion(a[0],a[1],a[2]));
     psb->translate(x);
     psb->setTotalMass(50,true);
     psb->generateClusters(64);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     return(psb);
 }
static void Ctor_Gear (SoftDemo * pdemo, const btVector3 & pos, btScalar speed) static
Definition at line 1059 of file SoftDemo.cpp.
 {
     btTransform startTransform;
     startTransform.setIdentity();
     startTransform.setOrigin(pos);
     btCompoundShape*    shape=new btCompoundShape();
 #if 1
     shape->addChildShape(btTransform(btQuaternion(0,0,0)),new btBoxShape(btVector3(5,1,6)));
     shape->addChildShape(btTransform(btQuaternion(0,0,SIMD_HALF_PI)),new btBoxShape(btVector3(5,1,6)));
 #else
     shape->addChildShape(btTransform(btQuaternion(0,0,0)),new btCylinderShapeZ(btVector3(5,1,7)));
     shape->addChildShape(btTransform(btQuaternion(0,0,SIMD_HALF_PI)),new btBoxShape(btVector3(4,1,8)));
 #endif
     btRigidBody*        body=pdemo->localCreateRigidBody(10,startTransform,shape);
     body->setFriction(1);
     btDynamicsWorld*    world=pdemo->getDynamicsWorld();
     btHingeConstraint*  hinge=new btHingeConstraint(*body,btTransform::getIdentity());
     if(speed!=0) hinge->enableAngularMotor(true,speed,3);
     world->addConstraint(hinge);
 }
static void Ctor_LinearStair (SoftDemo * pdemo, const btVector3 & org, const btVector3 & sizes, btScalar angle, int count) static
Definition at line 412 of file SoftDemo.cpp.
Referenced by Init_ClusterCar(), Init_Pressure(), and Init_Volume().
 {
     btBoxShape* shape=new btBoxShape(sizes);
     for(int i=0;i<count;++i)
     {
         btTransform startTransform;
         startTransform.setIdentity();
         startTransform.setOrigin(org+btVector3(sizes.x()*i*2,sizes.y()*i*2,0));
         btRigidBody* body=pdemo->localCreateRigidBody(0,startTransform,shape);
         body->setFriction(1);
     }
 }
static void Ctor_RbUpStack (SoftDemo * pdemo, int count) static
Definition at line 353 of file SoftDemo.cpp.
Referenced by Init_Cloth(), Init_ClusterCar(), and Init_ClusterCollide1().
 {
     float               mass=10;
     btCompoundShape* cylinderCompound = new btCompoundShape;
     btCollisionShape* cylinderShape = new btCylinderShapeX(btVector3(4,1,1));
     btCollisionShape* boxShape = new btBoxShape(btVector3(4,1,1));
     btTransform localTransform;
     localTransform.setIdentity();
     cylinderCompound->addChildShape(localTransform,boxShape);
     btQuaternion orn(SIMD_HALF_PI,0,0);
     localTransform.setRotation(orn);
     //  localTransform.setOrigin(btVector3(1,1,1));
     cylinderCompound->addChildShape(localTransform,cylinderShape);
     btCollisionShape*   shape[]={cylinderCompound,
         new btBoxShape(btVector3(1,1,1)),
         new btSphereShape(1.5)
     };
     static const int    nshapes=sizeof(shape)/sizeof(shape[0]);
     for(int i=0;i<count;++i)
     {
         btTransform startTransform;
         startTransform.setIdentity();
         startTransform.setOrigin(btVector3(0,2+6*i,0));
         pdemo->localCreateRigidBody(mass,startTransform,shape[i%nshapes]);
         //pdemo->localCreateRigidBody(mass,startTransform,shape[0]);
     }
 }
static btSoftBody* Ctor_SoftBoulder (SoftDemo * pdemo, const btVector3 & p, const btVector3 & s, int np, int id) static
Definition at line 450 of file SoftDemo.cpp.
 {
     btAlignedObjectArray<btVector3> pts;
     if(id) srand(id);
     for(int i=0;i<np;++i)
     {
         pts.push_back(Vector3Rand()*s+p);
     }
     btSoftBody*     psb=btSoftBodyHelpers::CreateFromConvexHull(pdemo->m_softBodyWorldInfo,&pts[0],pts.size());
     psb->generateBendingConstraints(2);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     return(psb);
 }
static btSoftBody* Ctor_SoftBox (SoftDemo * pdemo, const btVector3 & p, const btVector3 & s) static
Definition at line 428 of file SoftDemo.cpp.
Referenced by Init_Friction().
 {
     const btVector3 h=s*0.5;
     const btVector3 c[]={   p+h*btVector3(-1,-1,-1),
         p+h*btVector3(+1,-1,-1),
         p+h*btVector3(-1,+1,-1),
         p+h*btVector3(+1,+1,-1),
         p+h*btVector3(-1,-1,+1),
         p+h*btVector3(+1,-1,+1),
         p+h*btVector3(-1,+1,+1),
         p+h*btVector3(+1,+1,+1)};
     btSoftBody*     psb=btSoftBodyHelpers::CreateFromConvexHull(pdemo->m_softBodyWorldInfo,c,8);
     psb->generateBendingConstraints(2);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     return(psb);
 }
static void Init_Aero (SoftDemo * pdemo) static
Definition at line 713 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     const btScalar  s=2;
     const btScalar  h=10;
     const int       segments=6;
     const int       count=50;
     for(int i=0;i<count;++i)
     {
         btSoftBody*     psb=btSoftBodyHelpers::CreatePatch(pdemo->m_softBodyWorldInfo,btVector3(-s,h,-s),
             btVector3(+s,h,-s),
             btVector3(-s,h,+s),
             btVector3(+s,h,+s),
             segments,segments,
             0,true);
         btSoftBody::Material*   pm=psb->appendMaterial();
         pm->m_flags             -=  btSoftBody::fMaterial::DebugDraw;
         psb->generateBendingConstraints(2,pm);
         psb->m_cfg.kLF          =   0.004;
         psb->m_cfg.kDG          =   0.0003;
         psb->m_cfg.aeromodel    =   btSoftBody::eAeroModel::V_TwoSided;
         btTransform     trs;
         btQuaternion    rot;
         btVector3       ra=Vector3Rand()*0.1;
         btVector3       rp=Vector3Rand()*15+btVector3(0,20,80);
         rot.setEuler(SIMD_PI/8+ra.x(),-SIMD_PI/7+ra.y(),ra.z());
         trs.setIdentity();
         trs.setOrigin(rp);
         trs.setRotation(rot);
         psb->transform(trs);
         psb->setTotalMass(0.1);
         psb->addForce(btVector3(0,2,0),0);
         pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     }
     pdemo->m_autocam=true;
 }
static void Init_Aero2 (SoftDemo * pdemo) static
Definition at line 751 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     const btScalar  s=5;
     const int       segments=10;
     const int       count=5;
     btVector3 pos(-s*segments, 0, 0);
     btScalar gap = 0.5;
     for(int i=0;i<count;++i)
     {
         btSoftBody*     psb=btSoftBodyHelpers::CreatePatch( pdemo->m_softBodyWorldInfo,btVector3(-s,0,-s*3),
             btVector3(+s,0,-s*3),
             btVector3(-s,0,+s),
             btVector3(+s,0,+s),
             segments,segments*3,
             1+2,true);
         psb->getCollisionShape()->setMargin(0.5);
         btSoftBody::Material* pm=psb->appendMaterial();
         pm->m_kLST      =   0.0004;
         pm->m_flags     -=  btSoftBody::fMaterial::DebugDraw;
         psb->generateBendingConstraints(2,pm);
         psb->m_cfg.kLF          =   0.05;
         psb->m_cfg.kDG          =   0.01;
         //psb->m_cfg.kLF            =   0.004;
         //psb->m_cfg.kDG            =   0.0003;
         psb->m_cfg.piterations = 2;
         psb->m_cfg.aeromodel    =   btSoftBody::eAeroModel::V_TwoSidedLiftDrag;
         psb->setWindVelocity(btVector3(4, -12.0, -25.0));
         btTransform     trs;
         btQuaternion    rot;
         pos += btVector3(s*2 + gap, 0, 0);
         rot.setRotation(btVector3(1, 0, 0), btScalar(SIMD_PI/2));
         trs.setIdentity();
         trs.setOrigin(pos);
         trs.setRotation(rot);
         psb->transform(trs);
         psb->setTotalMass(2.0);
         pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     }
     pdemo->m_autocam=true;
 }
static void Init_Bending (SoftDemo * pdemo) static
Definition at line 903 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     const btScalar  s=4;
     const btVector3 x[]={   btVector3(-s,0,-s),
         btVector3(+s,0,-s),
         btVector3(+s,0,+s),
         btVector3(-s,0,+s)};
     const btScalar  m[]={   0,0,0,1};
     btSoftBody*     psb=new btSoftBody(&pdemo->m_softBodyWorldInfo,4,x,m);
     psb->appendLink(0,1);
     psb->appendLink(1,2);
     psb->appendLink(2,3);
     psb->appendLink(3,0);
     psb->appendLink(0,2);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
 }
static void Init_Bunny (SoftDemo * pdemo) static
Definition at line 952 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     btSoftBody* psb=btSoftBodyHelpers::CreateFromTriMesh(pdemo->m_softBodyWorldInfo,gVerticesBunny,
         &gIndicesBunny[0][0],
         BUNNY_NUM_TRIANGLES);
     btSoftBody::Material*   pm=psb->appendMaterial();
     pm->m_kLST              =   0.5;
     pm->m_flags             -=  btSoftBody::fMaterial::DebugDraw;
     psb->generateBendingConstraints(2,pm);
     psb->m_cfg.piterations  =   2;
     psb->m_cfg.kDF          =   0.5;
     psb->randomizeConstraints();
     psb->scale(btVector3(6,6,6));
     psb->setTotalMass(100,true);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     pdemo->m_cutting=true;
 }
static void Init_BunnyMatch (SoftDemo * pdemo) static
Definition at line 975 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     btSoftBody* psb=btSoftBodyHelpers::CreateFromTriMesh(pdemo->m_softBodyWorldInfo,    gVerticesBunny,
         &gIndicesBunny[0][0],
         BUNNY_NUM_TRIANGLES);
     psb->m_cfg.kDF              =   0.5;
     psb->m_cfg.kMT              =   0.05;
     psb->m_cfg.piterations      =   5;
     psb->randomizeConstraints();
     psb->scale(btVector3(6,6,6));
     psb->setTotalMass(100,true);
     psb->setPose(false,true);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
 }
static void Init_CapsuleCollision (SoftDemo * pdemo) static
Definition at line 557 of file SoftDemo.cpp.
 {
 #ifdef USE_AMD_OPENCL
     btAlignedObjectArray<btSoftBody*> emptyArray;
     if (g_openCLSIMDSolver)
         g_openCLSIMDSolver->optimize(emptyArray);
 #endif //USE_AMD_OPENCL
         //TRACEDEMO
     const btScalar  s=4;
     const btScalar  h=6;
     const int       r=20;
     btTransform startTransform;
     startTransform.setIdentity();
     startTransform.setOrigin(btVector3(0,h-2,0));
     btCollisionShape* capsuleShape= new btCapsuleShapeX(1,5);
     capsuleShape->setMargin( 0.5 );
     //  capsule->setLocalScaling(btVector3(5,1,1));
 //  btRigidBody*        body=pdemo->localCreateRigidBody(20,startTransform,capsuleShape);
     btRigidBody*        body=pdemo->localCreateRigidBody(0,startTransform,capsuleShape);
     body->setFriction( 0.8f );
     int fixed=0;//4+8;
     btSoftBody*     psb=btSoftBodyHelpers::CreatePatch(pdemo->m_softBodyWorldInfo,btVector3(-s,h,-s),
         btVector3(+s,h,-s),
         btVector3(-s,h,+s),
         btVector3(+s,h,+s),r,r,fixed,true);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     psb->setTotalMass(0.1);
     psb->m_cfg.piterations = 10;
     psb->m_cfg.citerations = 10;
     psb->m_cfg.diterations = 10;
 //  psb->m_cfg.viterations = 10;
     //  psb->appendAnchor(0,body);
 //  psb->appendAnchor(r-1,body);
 //  pdemo->m_cutting=true;
 }
static void Init_Cloth (SoftDemo * pdemo) static
Definition at line 925 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     const btScalar  s=8;
     btSoftBody*     psb=btSoftBodyHelpers::CreatePatch( pdemo->m_softBodyWorldInfo,btVector3(-s,0,-s),
         btVector3(+s,0,-s),
         btVector3(-s,0,+s),
         btVector3(+s,0,+s),
         31,31,
         //      31,31,
         1+2+4+8,true);
     psb->getCollisionShape()->setMargin(0.5);
     btSoftBody::Material* pm=psb->appendMaterial();
     pm->m_kLST      =   0.4;
     pm->m_flags     -=  btSoftBody::fMaterial::DebugDraw;
     psb->generateBendingConstraints(2,pm);
     psb->setTotalMass(150);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     Ctor_RbUpStack(pdemo,10);
     pdemo->m_cutting=true;
 }
static void Init_ClothAttach (SoftDemo * pdemo) static
Definition at line 518 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     const btScalar  s=4;
     const btScalar  h=6;
     const int       r=9;
     btSoftBody*     psb=btSoftBodyHelpers::CreatePatch(pdemo->m_softBodyWorldInfo,btVector3(-s,h,-s),
         btVector3(+s,h,-s),
         btVector3(-s,h,+s),
         btVector3(+s,h,+s),r,r,4+8,true);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     btTransform startTransform;
     startTransform.setIdentity();
     startTransform.setOrigin(btVector3(0,h,-(s+3.5)));
     btRigidBody*        body=pdemo->localCreateRigidBody(20,startTransform,new btBoxShape(btVector3(s,1,3)));
     psb->appendAnchor(0,body);
     psb->appendAnchor(r-1,body);
     pdemo->m_cutting=true;
 }
static void Init_ClusterCar (SoftDemo * pdemo) static
Definition at line 1292 of file SoftDemo.cpp.
 {
     pdemo->setAzi(180);
     const btVector3     origin(100,80,0);
     const btQuaternion  orientation(-SIMD_PI/2,0,0);
     const btScalar  widthf=8;
     const btScalar  widthr=9;
     const btScalar  length=8;
     const btScalar  height=4;
     const btVector3 wheels[]=   {
         btVector3(+widthf,-height,+length), // Front left
         btVector3(-widthf,-height,+length), // Front right
         btVector3(+widthr,-height,-length), // Rear left
         btVector3(-widthr,-height,-length), // Rear right
     };
     btSoftBody* pa=Ctor_ClusterBunny(pdemo,btVector3(0,0,0),btVector3(0,0,0));
     btSoftBody* pfl=Ctor_ClusterTorus(pdemo,wheels[0],btVector3(0,0,SIMD_HALF_PI),btVector3(2,4,2));
     btSoftBody* pfr=Ctor_ClusterTorus(pdemo,wheels[1],btVector3(0,0,SIMD_HALF_PI),btVector3(2,4,2));
     btSoftBody* prl=Ctor_ClusterTorus(pdemo,wheels[2],btVector3(0,0,SIMD_HALF_PI),btVector3(2,5,2));
     btSoftBody* prr=Ctor_ClusterTorus(pdemo,wheels[3],btVector3(0,0,SIMD_HALF_PI),btVector3(2,5,2));
     pfl->m_cfg.kDF  =
         pfr->m_cfg.kDF  =
         prl->m_cfg.kDF  =
         prr->m_cfg.kDF  =   1;
     btSoftBody::LJoint::Specs   lspecs;
     lspecs.cfm      =   1;
     lspecs.erp      =   1;
     lspecs.position =   btVector3(0,0,0);
     lspecs.position=wheels[0];pa->appendLinearJoint(lspecs,pfl);
     lspecs.position=wheels[1];pa->appendLinearJoint(lspecs,pfr);
     lspecs.position=wheels[2];pa->appendLinearJoint(lspecs,prl);
     lspecs.position=wheels[3];pa->appendLinearJoint(lspecs,prr);
     btSoftBody::AJoint::Specs   aspecs;
     aspecs.cfm      =   1;
     aspecs.erp      =   1;
     aspecs.axis     =   btVector3(1,0,0);
     aspecs.icontrol =   &steercontrol_f;
     pa->appendAngularJoint(aspecs,pfl);
     pa->appendAngularJoint(aspecs,pfr);
     aspecs.icontrol =   &motorcontrol;
     pa->appendAngularJoint(aspecs,prl);
     pa->appendAngularJoint(aspecs,prr);
     pa->rotate(orientation);
     pfl->rotate(orientation);
     pfr->rotate(orientation);
     prl->rotate(orientation);
     prr->rotate(orientation);
     pa->translate(origin);
     pfl->translate(origin);
     pfr->translate(origin);
     prl->translate(origin);
     prr->translate(origin);
     pfl->m_cfg.piterations  =
         pfr->m_cfg.piterations  =
         prl->m_cfg.piterations  =
         prr->m_cfg.piterations  = 1;
     pfl->m_clusters[0]->m_matching  =
         pfr->m_clusters[0]->m_matching  =
         prl->m_clusters[0]->m_matching  =
         prr->m_clusters[0]->m_matching  = 0.05;
     pfl->m_clusters[0]->m_ndamping  =
         pfr->m_clusters[0]->m_ndamping  =
         prl->m_clusters[0]->m_ndamping  =
         prr->m_clusters[0]->m_ndamping  = 0.05;
     Ctor_LinearStair(pdemo,btVector3(0,-8,0),btVector3(3,2,40),0,20);
     Ctor_RbUpStack(pdemo,50);
     pdemo->m_autocam=true;
 }
static void Init_ClusterCollide1 (SoftDemo * pdemo) static
pass zero in generateClusters to create cluster for each tetrahedron or triangle
Definition at line 1173 of file SoftDemo.cpp.
 {
     const btScalar  s=8;
     btSoftBody*     psb=btSoftBodyHelpers::CreatePatch( pdemo->m_softBodyWorldInfo,btVector3(-s,0,-s),
         btVector3(+s,0,-s),
         btVector3(-s,0,+s),
         btVector3(+s,0,+s),
         17,17,//9,9,//31,31,
         1+2+4+8,
         true);
     btSoftBody::Material* pm=psb->appendMaterial();
     pm->m_kLST      =   0.4;
     pm->m_flags     -=  btSoftBody::fMaterial::DebugDraw;
     psb->m_cfg.kDF  =   1;
     psb->m_cfg.kSRHR_CL     =   1;
     psb->m_cfg.kSR_SPLT_CL  =   0;
     psb->m_cfg.collisions   =   btSoftBody::fCollision::CL_SS+
         btSoftBody::fCollision::CL_RS;
     psb->generateBendingConstraints(2,pm);
     psb->getCollisionShape()->setMargin(0.05);
     psb->setTotalMass(50);
     psb->generateClusters(0);
     //psb->generateClusters(64);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     Ctor_RbUpStack(pdemo,10);
 }
static void Init_ClusterCollide2 (SoftDemo * pdemo) static
Definition at line 1207 of file SoftDemo.cpp.
 {
     struct Functor
     {
         static btSoftBody* Create(SoftDemo* pdemo,const btVector3& x,const btVector3& a)
         {
             btSoftBody* psb=btSoftBodyHelpers::CreateFromTriMesh(pdemo->m_softBodyWorldInfo,gVertices,
                 &gIndices[0][0],
                 NUM_TRIANGLES);
             btSoftBody::Material* pm=psb->appendMaterial();
             pm->m_flags     -=  btSoftBody::fMaterial::DebugDraw;
             psb->generateBendingConstraints(2,pm);
             psb->m_cfg.piterations=2;
             psb->m_cfg.kDF          =1;
             psb->m_cfg.kSSHR_CL     =1;
             psb->m_cfg.kSS_SPLT_CL  =0;
             psb->m_cfg.kSKHR_CL     =0.1f;
             psb->m_cfg.kSK_SPLT_CL  =1;
             psb->m_cfg.collisions=  btSoftBody::fCollision::CL_SS+
                 btSoftBody::fCollision::CL_RS;
             psb->randomizeConstraints();
             btMatrix3x3 m;
             m.setEulerZYX(a.x(),a.y(),a.z());
             psb->transform(btTransform(m,x));
             psb->scale(btVector3(2,2,2));
             psb->setTotalMass(50,true);
             psb->generateClusters(16);
             pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
             return(psb);
         }
     };
     for(int i=0;i<3;++i)
     {
         Functor::Create(pdemo,btVector3(3*i,2,0),btVector3(SIMD_PI/2*(1-(i&1)),SIMD_PI/2*(i&1),0));
     }
 }
static void Init_ClusterCombine (SoftDemo * pdemo) static
Definition at line 1267 of file SoftDemo.cpp.
 {
     const btVector3 sz(2,4,2);
     btSoftBody* psb0=Ctor_ClusterTorus(pdemo,btVector3(0,8,0),btVector3(SIMD_PI/2,0,SIMD_HALF_PI),sz);
     btSoftBody* psb1=Ctor_ClusterTorus(pdemo,btVector3(0,8,10),btVector3(SIMD_PI/2,0,SIMD_HALF_PI),sz);
     btSoftBody* psbs[]={psb0,psb1};
     for(int j=0;j<2;++j)
     {
         psbs[j]->m_cfg.kDF=1;
         psbs[j]->m_cfg.kDP=0;
         psbs[j]->m_cfg.piterations=1;
         psbs[j]->m_clusters[0]->m_matching  =   0.05;
         psbs[j]->m_clusters[0]->m_ndamping  =   0.05;
     }
     btSoftBody::AJoint::Specs   aj;
     aj.axis     =   btVector3(0,0,1);
     aj.icontrol =   &motorcontrol;
     psb0->appendAngularJoint(aj,psb1);
     btSoftBody::LJoint::Specs   lj;
     lj.position =   btVector3(0,8,5);
     psb0->appendLinearJoint(lj,psb1);
 }
static void Init_ClusterDeform (SoftDemo * pdemo) static
Definition at line 1165 of file SoftDemo.cpp.
 {
     btSoftBody*     psb=Ctor_ClusterTorus(pdemo,btVector3(0,0,0),btVector3(SIMD_PI/2,0,SIMD_HALF_PI));
     psb->generateClusters(8);
     psb->m_cfg.kDF=1;
 }
static void Init_ClusterHinge (SoftDemo * pdemo) static
Definition at line 1256 of file SoftDemo.cpp.
 {
     btSoftBody*     psb=Ctor_ClusterTorus(pdemo,btVector3(0,0,0),btVector3(SIMD_PI/2,0,SIMD_HALF_PI));
     btRigidBody*    prb=Ctor_BigPlate(pdemo,50,8);
     psb->m_cfg.kDF=1;
     btSoftBody::AJoint::Specs   aj;
     aj.axis =   btVector3(0,0,1);
     psb->appendAngularJoint(aj,prb);
 }
static void Init_ClusterRobot (SoftDemo * pdemo) static
Definition at line 1371 of file SoftDemo.cpp.
 {
     struct Functor
     {
         static btSoftBody*  CreateBall(SoftDemo* pdemo,const btVector3& pos)
         {
             btSoftBody* psb=btSoftBodyHelpers::CreateEllipsoid(pdemo->m_softBodyWorldInfo,pos,btVector3(1,1,1)*3,512);
             psb->m_materials[0]->m_kLST =   0.45;
             psb->m_cfg.kVC              =   20;
             psb->setTotalMass(50,true);
             psb->setPose(true,false);
             psb->generateClusters(1);
             pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
             return(psb);
         }
     };
     const btVector3     base=btVector3(0,25,8);
     btSoftBody*         psb0=Functor::CreateBall(pdemo,base+btVector3(-8,0,0));
     btSoftBody*         psb1=Functor::CreateBall(pdemo,base+btVector3(+8,0,0));
     btSoftBody*         psb2=Functor::CreateBall(pdemo,base+btVector3(0,0,+8*btSqrt(2)));
     const btVector3     ctr=(psb0->clusterCom(0)+psb1->clusterCom(0)+psb2->clusterCom(0))/3;
     btCylinderShape*    pshp=new btCylinderShape(btVector3(8,1,8));
     btRigidBody*        prb=pdemo->localCreateRigidBody(50,btTransform(btQuaternion(0,0,0),ctr+btVector3(0,5,0)),pshp);
     btSoftBody::LJoint::Specs   ls;
     ls.erp=0.5f;
     ls.position=psb0->clusterCom(0);psb0->appendLinearJoint(ls,prb);
     ls.position=psb1->clusterCom(0);psb1->appendLinearJoint(ls,prb);
     ls.position=psb2->clusterCom(0);psb2->appendLinearJoint(ls,prb);
     btBoxShape*         pbox=new btBoxShape(btVector3(20,1,40));
     btRigidBody*        pgrn=pdemo->localCreateRigidBody(0,btTransform(btQuaternion(0,-SIMD_HALF_PI/2,0),btVector3(0,0,0)),pbox);
     pdemo->m_autocam=true;
 }
static void Init_ClusterSocket (SoftDemo * pdemo) static
Definition at line 1245 of file SoftDemo.cpp.
 {
     btSoftBody*     psb=Ctor_ClusterTorus(pdemo,btVector3(0,0,0),btVector3(SIMD_PI/2,0,SIMD_HALF_PI));
     btRigidBody*    prb=Ctor_BigPlate(pdemo,50,8);
     psb->m_cfg.kDF=1;
     btSoftBody::LJoint::Specs   lj;
     lj.position =   btVector3(0,5,0);
     psb->appendLinearJoint(lj,prb);
 }
static void Init_ClusterStackMixed (SoftDemo * pdemo) static
Definition at line 1418 of file SoftDemo.cpp.
 {
     for(int i=0;i<10;++i)
     {
         if((i+1)&1)
         {
             Ctor_BigPlate(pdemo,50,-9+4.25*i);
         }
         else
         {
             btSoftBody* psb=Ctor_ClusterTorus(pdemo,btVector3(0,-9+4.25*i,0),btVector3(0,0,0));
             psb->m_cfg.kDF=1;
         }
     }
 }
static void Init_ClusterStackSoft (SoftDemo * pdemo) static
Definition at line 1408 of file SoftDemo.cpp.
 {
     for(int i=0;i<10;++i)
     {
         btSoftBody* psb=Ctor_ClusterTorus(pdemo,btVector3(0,-9+8.25*i,0),btVector3(0,0,0));
         psb->m_cfg.kDF=1;
     }
 }
static void Init_Collide (SoftDemo * pdemo) static
Definition at line 604 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     struct Functor
     {
         static btSoftBody* Create(SoftDemo* pdemo,const btVector3& x,const btVector3& a)
         {
             btSoftBody* psb=btSoftBodyHelpers::CreateFromTriMesh(pdemo->m_softBodyWorldInfo,gVertices,
                 &gIndices[0][0],
                 NUM_TRIANGLES);
             psb->generateBendingConstraints(2);
             psb->m_cfg.piterations=2;
             psb->m_cfg.collisions|=btSoftBody::fCollision::VF_SS;
             psb->randomizeConstraints();
             btMatrix3x3 m;
             m.setEulerZYX(a.x(),a.y(),a.z());
             psb->transform(btTransform(m,x));
             psb->scale(btVector3(2,2,2));
             psb->setTotalMass(50,true);
             pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
             return(psb);
         }
     };
     for(int i=0;i<3;++i)
     {
         Functor::Create(pdemo,btVector3(3*i,2,0),btVector3(SIMD_PI/2*(1-(i&1)),SIMD_PI/2*(i&1),0));
     }
     pdemo->m_cutting=true;
 }
static void Init_Collide2 (SoftDemo * pdemo) static
Definition at line 637 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     struct Functor
     {
         static btSoftBody* Create(SoftDemo* pdemo,const btVector3& x,const btVector3& a)
         {
             btSoftBody* psb=btSoftBodyHelpers::CreateFromTriMesh(pdemo->m_softBodyWorldInfo,gVerticesBunny,
                 &gIndicesBunny[0][0],
                 BUNNY_NUM_TRIANGLES);
             btSoftBody::Material*   pm=psb->appendMaterial();
             pm->m_kLST              =   0.5;
             pm->m_flags             -=  btSoftBody::fMaterial::DebugDraw;
             psb->generateBendingConstraints(2,pm);
             psb->m_cfg.piterations  =   2;
             psb->m_cfg.kDF          =   0.5;
             psb->m_cfg.collisions   |=  btSoftBody::fCollision::VF_SS;
             psb->randomizeConstraints();
             btMatrix3x3 m;
             m.setEulerZYX(a.x(),a.y(),a.z());
             psb->transform(btTransform(m,x));
             psb->scale(btVector3(6,6,6));
             psb->setTotalMass(100,true);
             pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
             return(psb);
         }
     };
     for(int i=0;i<3;++i)
     {
         Functor::Create(pdemo,btVector3(0,-1+5*i,0),btVector3(0,SIMD_PI/2*(i&1),0));
     }
     pdemo->m_cutting=true;
 }
static void Init_Collide3 (SoftDemo * pdemo) static
Definition at line 674 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     {
         const btScalar  s=8;
         btSoftBody*     psb=btSoftBodyHelpers::CreatePatch( pdemo->m_softBodyWorldInfo,btVector3(-s,0,-s),
             btVector3(+s,0,-s),
             btVector3(-s,0,+s),
             btVector3(+s,0,+s),
             15,15,1+2+4+8,true);
         psb->m_materials[0]->m_kLST =   0.4;
         psb->m_cfg.collisions       |=  btSoftBody::fCollision::VF_SS;
         psb->setTotalMass(150);
         pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     }
     {
         const btScalar  s=4;
         const btVector3 o=btVector3(5,10,0);
         btSoftBody*     psb=btSoftBodyHelpers::CreatePatch( pdemo->m_softBodyWorldInfo,
             btVector3(-s,0,-s)+o,
             btVector3(+s,0,-s)+o,
             btVector3(-s,0,+s)+o,
             btVector3(+s,0,+s)+o,
             7,7,0,true);
         btSoftBody::Material*   pm=psb->appendMaterial();
         pm->m_kLST              =   0.1;
         pm->m_flags             -=  btSoftBody::fMaterial::DebugDraw;
         psb->generateBendingConstraints(2,pm);
         psb->m_materials[0]->m_kLST =   0.5;
         psb->m_cfg.collisions       |=  btSoftBody::fCollision::VF_SS;
         psb->setTotalMass(150);
         pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
         pdemo->m_cutting=true;
     }
 }
static void Init_Cutting1 (SoftDemo * pdemo) static
Definition at line 1039 of file SoftDemo.cpp.
 {
     const btScalar  s=6;
     const btScalar  h=2;
     const int       r=16;
     const btVector3 p[]={   btVector3(+s,h,-s),
         btVector3(-s,h,-s),
         btVector3(+s,h,+s),
         btVector3(-s,h,+s)};
     btSoftBody* psb=btSoftBodyHelpers::CreatePatch(pdemo->m_softBodyWorldInfo,p[0],p[1],p[2],p[3],r,r,1+2+4+8,true);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     psb->m_cfg.piterations=1;
     pdemo->m_cutting=true;
 }
static void Init_Friction (SoftDemo * pdemo) static
Definition at line 806 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     const btScalar  bs=2;
     const btScalar  ts=bs+bs/4;
     for(int i=0,ni=20;i<ni;++i)
     {
         const btVector3 p(-ni*ts/2+i*ts,-10+bs,40);
         btSoftBody*     psb=Ctor_SoftBox(pdemo,p,btVector3(bs,bs,bs));
         psb->m_cfg.kDF  =   0.1 * ((i+1)/(btScalar)ni);
         psb->addVelocity(btVector3(0,0,-10));
     }
 }
static void Init_Impact (SoftDemo * pdemo) static
Definition at line 542 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     btSoftBody* psb=btSoftBodyHelpers::CreateRope(pdemo->m_softBodyWorldInfo,   btVector3(0,0,0),
         btVector3(0,-1,0),
         0,
         1);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     psb->m_cfg.kCHR=0.5;
     btTransform startTransform;
     startTransform.setIdentity();
     startTransform.setOrigin(btVector3(0,20,0));
     pdemo->localCreateRigidBody(10,startTransform,new btBoxShape(btVector3(2,2,2)));
 }
static void Init_Pressure (SoftDemo * pdemo) static
Definition at line 823 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     btSoftBody* psb=btSoftBodyHelpers::CreateEllipsoid(pdemo->m_softBodyWorldInfo,btVector3(35,25,0),
         btVector3(1,1,1)*3,
         512);
     psb->m_materials[0]->m_kLST =   0.1;
     psb->m_cfg.kDF              =   1;
     psb->m_cfg.kDP              =   0.001; // fun factor...
     psb->m_cfg.kPR              =   2500;
     psb->setTotalMass(30,true);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     Ctor_BigPlate(pdemo);
     Ctor_LinearStair(pdemo,btVector3(0,0,0),btVector3(2,1,5),0,10);
     pdemo->m_autocam=true;
 }
static void Init_RopeAttach (SoftDemo * pdemo) static
Definition at line 491 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     pdemo->m_softBodyWorldInfo.m_sparsesdf.RemoveReferences(0);
     struct  Functors
     {
         static btSoftBody* CtorRope(SoftDemo* pdemo,const btVector3& p)
         {
             btSoftBody* psb=btSoftBodyHelpers::CreateRope(pdemo->m_softBodyWorldInfo,p,p+btVector3(10,0,0),8,1);
             psb->setTotalMass(50);
             pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
             return(psb);
         }
     };
     btTransform startTransform;
     startTransform.setIdentity();
     startTransform.setOrigin(btVector3(12,8,0));
     btRigidBody*        body=pdemo->localCreateRigidBody(50,startTransform,new btBoxShape(btVector3(2,6,2)));
     btSoftBody* psb0=Functors::CtorRope(pdemo,btVector3(0,8,-1));
     btSoftBody* psb1=Functors::CtorRope(pdemo,btVector3(0,8,+1));
     psb0->appendAnchor(psb0->m_nodes.size()-1,body);
     psb1->appendAnchor(psb1->m_nodes.size()-1,body);
 }
static void Init_Ropes (SoftDemo * pdemo) static
Definition at line 470 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     const int n=15;
     for(int i=0;i<n;++i)
     {
         btSoftBody* psb=btSoftBodyHelpers::CreateRope(pdemo->m_softBodyWorldInfo,   btVector3(-10,0,i*0.25),
             btVector3(10,0,i*0.25),
             16,
             1+2);
         psb->m_cfg.piterations      =   4;
         psb->m_materials[0]->m_kLST =   0.1+(i/(btScalar)(n-1))*0.9;
         psb->setTotalMass(20);
         pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     }
 }
static void Init_Sticks (SoftDemo * pdemo) static
Definition at line 866 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     const int       n=16;
     const int       sg=4;
     const btScalar  sz=5;
     const btScalar  hg=4;
     const btScalar  in=1/(btScalar)(n-1);
     for(int y=0;y<n;++y)
     {
         for(int x=0;x<n;++x)
         {
             const btVector3 org(-sz+sz*2*x*in,
                 -10,
                 -sz+sz*2*y*in);
             btSoftBody*     psb=btSoftBodyHelpers::CreateRope(  pdemo->m_softBodyWorldInfo, org,
                 org+btVector3(hg*0.001,hg,0),
                 sg,
                 1);
             psb->m_cfg.kDP      =   0.005;
             psb->m_cfg.kCHR     =   0.1;
             for(int i=0;i<3;++i)
             {
                 psb->generateBendingConstraints(2+i);
             }
             psb->setMass(1,0);
             psb->setTotalMass(0.01);
             pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
         }
     }
     Ctor_BigBall(pdemo);
 }
static void Init_TetraBunny (SoftDemo * pdemo) static
pass zero in generateClusters to create cluster for each tetrahedron or triangle
Definition at line 1438 of file SoftDemo.cpp.
 {
     btSoftBody* psb=btSoftBodyHelpers::CreateFromTetGenData(pdemo->m_softBodyWorldInfo,
                                                             TetraBunny::getElements(),
                                                             0,
                                                             TetraBunny::getNodes(),
                                                             false,true,true);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     psb->rotate(btQuaternion(SIMD_PI/2,0,0));
     psb->setVolumeMass(150);
     psb->m_cfg.piterations=2;
     //psb->m_cfg.piterations=1;
     pdemo->m_cutting=false;
     //psb->getCollisionShape()->setMargin(0.01);
     psb->m_cfg.collisions   =   btSoftBody::fCollision::CL_SS+  btSoftBody::fCollision::CL_RS
         //+ btSoftBody::fCollision::CL_SELF
         ;
     psb->generateClusters(0);
     //psb->m_materials[0]->m_kLST=.2;
     psb->m_cfg.kDF  =   10. ;
 }
static void Init_TetraCube (SoftDemo * pdemo) static
fix one vertex
Definition at line 1467 of file SoftDemo.cpp.
 {
     btSoftBody* psb=btSoftBodyHelpers::CreateFromTetGenData(pdemo->m_softBodyWorldInfo,
                                                             TetraCube::getElements(),
                                                             0,
                                                             TetraCube::getNodes(),
                                                             false,true,true);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     psb->scale(btVector3(4,4,4));
     psb->translate(btVector3(0,5,0));
     psb->setVolumeMass(300);
     //psb->setMass(0,0);
     //psb->setMass(10,0);
     //psb->setMass(20,0);
     psb->m_cfg.piterations=1;
     //psb->generateClusters(128);
     psb->generateClusters(16);
     //psb->getCollisionShape()->setMargin(0.5);
     psb->getCollisionShape()->setMargin(0.01);
     psb->m_cfg.collisions   =   btSoftBody::fCollision::CL_SS+  btSoftBody::fCollision::CL_RS
         //+ btSoftBody::fCollision::CL_SELF
         ;
     psb->m_materials[0]->m_kLST=0.8;
     pdemo->m_cutting=false;
 }
static void Init_Torus (SoftDemo * pdemo) static
Definition at line 995 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     btSoftBody* psb=btSoftBodyHelpers::CreateFromTriMesh(   pdemo->m_softBodyWorldInfo, gVertices,
         &gIndices[0][0],
         NUM_TRIANGLES);
     psb->generateBendingConstraints(2);
     psb->m_cfg.piterations=2;
     psb->randomizeConstraints();
     btMatrix3x3 m;
     m.setEulerZYX(SIMD_PI/2,0,0);
     psb->transform(btTransform(m,btVector3(0,4,0)));
     psb->scale(btVector3(2,2,2));
     psb->setTotalMass(50,true);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     pdemo->m_cutting=true;
 }
static void Init_TorusMatch (SoftDemo * pdemo) static
Definition at line 1018 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     btSoftBody* psb=btSoftBodyHelpers::CreateFromTriMesh(pdemo->m_softBodyWorldInfo,    gVertices,
         &gIndices[0][0],
         NUM_TRIANGLES);
     psb->m_materials[0]->m_kLST =   0.1;
     psb->m_cfg.kMT              =   0.05;
     psb->randomizeConstraints();
     btMatrix3x3 m;
     m.setEulerZYX(SIMD_PI/2,0,0);
     psb->transform(btTransform(m,btVector3(0,4,0)));
     psb->scale(btVector3(2,2,2));
     psb->setTotalMass(50,true);
     psb->setPose(false,true);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
 }
static void Init_Volume (SoftDemo * pdemo) static
Definition at line 845 of file SoftDemo.cpp.
 {
     //TRACEDEMO
     btSoftBody* psb=btSoftBodyHelpers::CreateEllipsoid(pdemo->m_softBodyWorldInfo,btVector3(35,25,0),
         btVector3(1,1,1)*3,
         512);
     psb->m_materials[0]->m_kLST =   0.45;
     psb->m_cfg.kVC              =   20;
     psb->setTotalMass(50,true);
     psb->setPose(true,false);
     pdemo->getSoftDynamicsWorld()->addSoftBody(psb);
     Ctor_BigPlate(pdemo);
     Ctor_LinearStair(pdemo,btVector3(0,0,0),btVector3(2,1,5),0,10);
     pdemo->m_autocam=true;
 }
void pickingPreTickCallback (btDynamicsWorld * world, btScalar timeStep)
for mouse picking
Definition at line 250 of file SoftDemo.cpp.
Referenced by SoftDemo::initPhysics().
 {
     SoftDemo* softDemo = (SoftDemo*)world->getWorldUserInfo();
     if(softDemo->m_drag)
     {
         const int               x=softDemo->m_lastmousepos[0];
         const int               y=softDemo->m_lastmousepos[1];
         const btVector3         rayFrom=softDemo->getCameraPosition();
         const btVector3         rayTo=softDemo->getRayTo(x,y);
         const btVector3         rayDir=(rayTo-rayFrom).normalized();
         const btVector3         N=(softDemo->getCameraTargetPosition()-softDemo->getCameraPosition()).normalized();
         const btScalar          O=btDot(softDemo->m_impact,N);
         const btScalar          den=btDot(N,rayDir);
         if((den*den)>0)
         {
             const btScalar          num=O-btDot(N,rayFrom);
             const btScalar          hit=num/den;
             if((hit>0)&&(hit<1500))
             {
                 softDemo->m_goal=rayFrom+rayDir*hit;
             }
         }
         btVector3               delta=softDemo->m_goal-softDemo->m_node->m_x;
         static const btScalar   maxdrag=10;
         if(delta.length2()>(maxdrag*maxdrag))
         {
             delta=delta.normalized()*maxdrag;
         }
         softDemo->m_node->m_v+=delta/timeStep;
     }
 }
static btScalar SignedUnitRand () inline static
Definition at line 339 of file SoftDemo.cpp.
Referenced by Vector3Rand().
 {
     return(UnitRand()*2-1);
 }
static btScalar UnitRand () inline static
Definition at line 334 of file SoftDemo.cpp.
Referenced by SignedUnitRand().
 {
     return(rand()/(btScalar)RAND_MAX);
 }
static btVector3 Vector3Rand () inline static
Definition at line 344 of file SoftDemo.cpp.
Referenced by Ctor_SoftBoulder(), and Init_Aero().
 {
     const btVector3 p=btVector3(SignedUnitRand(),SignedUnitRand(),SignedUnitRand());
     return(p.normalized());
 }
Variable Documentation
int current_demo =20
Definition at line 55 of file SoftDemo.cpp.
Referenced by SoftDemo::clientMoveAndDisplay(), SoftDemo::clientResetScene(), SoftDemo::keyboardCallback(), and SoftDemo::renderme().
void(* demofncs[])(SoftDemo *)
Initial value:
=
    {
        Init_Volume,
        Init_TetraCube,
    }
Definition at line 1502 of file SoftDemo.cpp.
Referenced by SoftDemo::clientMoveAndDisplay(), and SoftDemo::clientResetScene().
float eye[3]
btSoftBody implementation by Nathanael Presson
int* gGroundIndices =0 static
Definition at line 49 of file SoftDemo.cpp.
Referenced by SoftDemo::initPhysics().
btVector3* gGroundVertices =0 static
Definition at line 48 of file SoftDemo.cpp.
Referenced by SoftDemo::initPhysics().
int glutScreenHeight
int glutScreenWidth
int gNumManifold
const int gNumObjects = 1
Definition at line 62 of file SoftDemo.cpp.
int gOverlappingPairs
const int maxNumObjects = 32760
Definition at line 65 of file SoftDemo.cpp.
const int maxOverlap = 65535
Definition at line 46 of file SoftDemo.cpp.
const int maxProxies = 32766
Definition at line 45 of file SoftDemo.cpp.
Referenced by SoftDemo::initPhysics().
MotorControl motorcontrol static
Referenced by SoftDemo::clientResetScene(), Init_ClusterCar(), Init_ClusterCombine(), SoftDemo::initPhysics(), SoftDemo::keyboardCallback(), and SteerControl::Speed().
bool sDemoMode = false static
Definition at line 43 of file SoftDemo.cpp.
Referenced by SoftDemo::clientMoveAndDisplay(), SoftDemo::keyboardCallback(), and SoftDemo::renderme().
btRigidBody* staticBody = 0 static
Definition at line 51 of file SoftDemo.cpp.
SteerControl steercontrol_f(+1) static
Referenced by Init_ClusterCar(), and SoftDemo::keyboardCallback().
SteerControl steercontrol_r(-1) static
Referenced by SoftDemo::keyboardCallback().
const float TRIANGLE_SIZE =8.f
Definition at line 54 of file SoftDemo.cpp.
Referenced by SoftDemo::initPhysics().
btBvhTriangleMeshShape* trimeshShape =0 static
Definition at line 50 of file SoftDemo.cpp.
float waveheight = 5.f static
Definition at line 52 of file SoftDemo.cpp.
Referenced by SoftDemo::initPhysics().