RobotEvolver: stb_image.h File Reference
stb_image.h File Reference
#include <stdio.h>
Data Structures
struct stbi_io_callbacks
Macros
#define STBI_VERSION 1
Typedefs
typedef unsigned char stbi_uc
Enumerations
enum {
STBI_default = 0, STBI_grey = 1, STBI_grey_alpha = 2, STBI_rgb = 3,
STBI_rgb_alpha = 4
}
Functions
stbi_uc * stbi_load_from_memory (stbi_uc const *buffer, int len, int *x, int *y, int *comp, int req_comp)
STBI_NO_STDIO.
stbi_uc * stbi_load (char const *filename, int *x, int *y, int *comp, int req_comp)
stbi_uc * stbi_load_from_file (FILE *f, int *x, int *y, int *comp, int req_comp)
stbi_uc * stbi_load_from_callbacks (stbi_io_callbacks const *clbk, void *user, int *x, int *y, int *comp, int req_comp)
float * stbi_loadf_from_memory (stbi_uc const *buffer, int len, int *x, int *y, int *comp, int req_comp)
float * stbi_loadf (char const *filename, int *x, int *y, int *comp, int req_comp)
float * stbi_loadf_from_file (FILE *f, int *x, int *y, int *comp, int req_comp)
float * stbi_loadf_from_callbacks (stbi_io_callbacks const *clbk, void *user, int *x, int *y, int *comp, int req_comp)
void stbi_hdr_to_ldr_gamma (float gamma)
void stbi_hdr_to_ldr_scale (float scale)
void stbi_ldr_to_hdr_gamma (float gamma)
void stbi_ldr_to_hdr_scale (float scale)
int stbi_is_hdr_from_callbacks (stbi_io_callbacks const *clbk, void *user)
int stbi_is_hdr_from_memory (stbi_uc const *buffer, int len)
int stbi_is_hdr (char const *filename)
int stbi_is_hdr_from_file (FILE *f)
const char * stbi_failure_reason (void)
void stbi_image_free (void *retval_from_stbi_load)
int stbi_info_from_memory (stbi_uc const *buffer, int len, int *x, int *y, int *comp)
int stbi_info_from_callbacks (stbi_io_callbacks const *clbk, void *user, int *x, int *y, int *comp)
int stbi_info (char const *filename, int *x, int *y, int *comp)
int stbi_info_from_file (FILE *f, int *x, int *y, int *comp)
void stbi_set_unpremultiply_on_load (int flag_true_if_should_unpremultiply)
void stbi_convert_iphone_png_to_rgb (int flag_true_if_should_convert)
char * stbi_zlib_decode_malloc_guesssize (const char *buffer, int len, int initial_size, int *outlen)
char * stbi_zlib_decode_malloc (const char *buffer, int len, int *outlen)
int stbi_zlib_decode_buffer (char *obuffer, int olen, const char *ibuffer, int ilen)
char * stbi_zlib_decode_noheader_malloc (const char *buffer, int len, int *outlen)
int stbi_zlib_decode_noheader_buffer (char *obuffer, int olen, const char *ibuffer, int ilen)
Macro Definition Documentation
#define STBI_VERSION 1
Definition at line 196 of file stb_image.h.
Typedef Documentation
typedef unsigned char stbi_uc
Definition at line 208 of file stb_image.h.
Enumeration Type Documentation
anonymous enum
Enumerator
STBI_default
STBI_grey
STBI_grey_alpha
STBI_rgb
STBI_rgb_alpha
Definition at line 198 of file stb_image.h.
 {
    STBI_default = 0, // only used for req_comp
    STBI_grey       = 1,
    STBI_grey_alpha = 2,
    STBI_rgb        = 3,
    STBI_rgb_alpha  = 4
 };
Function Documentation
void stbi_convert_iphone_png_to_rgb (int flag_true_if_should_convert)
Definition at line 2298 of file stb_image.cpp.
 {
    stbi_de_iphone_flag = flag_true_if_should_convert;
 }
const char* stbi_failure_reason (void)
Definition at line 167 of file stb_image.cpp.
 {
    return failure_reason;
 }
void stbi_hdr_to_ldr_gamma (float gamma)
Definition at line 364 of file stb_image.cpp.
 { h2l_gamma_i = 1/gamma; }
void stbi_hdr_to_ldr_scale (float scale)
Definition at line 365 of file stb_image.cpp.
 { h2l_scale_i = 1/scale; }
void stbi_image_free (void * retval_from_stbi_load)
Definition at line 193 of file stb_image.cpp.
 {
    free(retval_from_stbi_load);
 }
int stbi_info (char const * filename, int * x, int * y, int * comp)
Definition at line 4218 of file stb_image.cpp.
 {
     FILE *f = fopen(filename, "rb");
     int result;
     if (!f) return e("can't fopen", "Unable to open file");
     result = stbi_info_from_file(f, x, y, comp);
     fclose(f);
     return result;
 }
int stbi_info_from_callbacks (stbi_io_callbacks const * clbk, void * user, int * x, int * y, int * comp)
Definition at line 4247 of file stb_image.cpp.
 {
    stbi s;
    start_callbacks(&s, (stbi_io_callbacks *) c, user);
    return stbi_info_main(&s,x,y,comp);
 }
int stbi_info_from_file (FILE * f, int * x, int * y, int * comp)
Definition at line 4228 of file stb_image.cpp.
Referenced by stbi_info().
 {
    int r;
    stbi s;
    long pos = ftell(f);
    start_file(&s, f);
    r = stbi_info_main(&s,x,y,comp);
    fseek(f,pos,SEEK_SET);
    return r;
 }
int stbi_info_from_memory (stbi_uc const * buffer, int len, int * x, int * y, int * comp)
Definition at line 4240 of file stb_image.cpp.
 {
    stbi s;
    start_mem(&s,buffer,len);
    return stbi_info_main(&s,x,y,comp);
 }
int stbi_is_hdr (char const * filename)
Definition at line 326 of file stb_image.cpp.
 {
    FILE *f = fopen(filename, "rb");
    int result=0;
    if (f) {
       result = stbi_is_hdr_from_file(f);
       fclose(f);
    }
    return result;
 }
int stbi_is_hdr_from_callbacks (stbi_io_callbacks const * clbk, void * user)
Definition at line 349 of file stb_image.cpp.
 {
    #ifndef STBI_NO_HDR
    stbi s;
    start_callbacks(&s, (stbi_io_callbacks *) clbk, user);
    return stbi_hdr_test(&s);
    #else
    return 0;
    #endif
 }
int stbi_is_hdr_from_file (FILE * f)
Definition at line 337 of file stb_image.cpp.
Referenced by stbi_is_hdr().
 {
    #ifndef STBI_NO_HDR
    stbi s;
    start_file(&s,f);
    return stbi_hdr_test(&s);
    #else
    return 0;
    #endif
 }
int stbi_is_hdr_from_memory (stbi_uc const * buffer, int len)
Definition at line 312 of file stb_image.cpp.
 {
    #ifndef STBI_NO_HDR
    stbi s;
    start_mem(&s,buffer,len);
    return stbi_hdr_test(&s);
    #else
    STBI_NOTUSED(buffer);
    STBI_NOTUSED(len);
    return 0;
    #endif
 }
void stbi_ldr_to_hdr_gamma (float gamma)
Definition at line 367 of file stb_image.cpp.
 { l2h_gamma = gamma; }
void stbi_ldr_to_hdr_scale (float scale)
Definition at line 368 of file stb_image.cpp.
 { l2h_scale = scale; }
stbi_uc* stbi_load (char const * filename, int * x, int * y, int * comp, int req_comp)
Definition at line 226 of file stb_image.cpp.
 {
    FILE *f = fopen(filename, "rb");
    unsigned char *result;
    if (!f) return epuc("can't fopen", "Unable to open file");
    result = stbi_load_from_file(f,x,y,comp,req_comp);
    fclose(f);
    return result;
 }
stbi_uc* stbi_load_from_callbacks (stbi_io_callbacks const * clbk, void * user, int * x, int * y, int * comp, int req_comp)
Definition at line 251 of file stb_image.cpp.
 {
    stbi s;
    start_callbacks(&s, (stbi_io_callbacks *) clbk, user);
    return stbi_load_main(&s,x,y,comp,req_comp);
 }
stbi_uc* stbi_load_from_file (FILE * f, int * x, int * y, int * comp, int req_comp)
Definition at line 236 of file stb_image.cpp.
Referenced by stbi_load().
 {
    stbi s;
    start_file(&s,f);
    return stbi_load_main(&s,x,y,comp,req_comp);
 }
stbi_uc* stbi_load_from_memory (stbi_uc const * buffer, int len, int * x, int * y, int * comp, int req_comp)
STBI_NO_STDIO.
Definition at line 244 of file stb_image.cpp.
 {
    stbi s;
    start_mem(&s,buffer,len);
    return stbi_load_main(&s,x,y,comp,req_comp);
 }
float* stbi_loadf (char const * filename, int * x, int * y, int * comp, int req_comp)
Definition at line 288 of file stb_image.cpp.
 {
    FILE *f = fopen(filename, "rb");
    float *result;
    if (!f) return epf("can't fopen", "Unable to open file");
    result = stbi_loadf_from_file(f,x,y,comp,req_comp);
    fclose(f);
    return result;
 }
float* stbi_loadf_from_callbacks (stbi_io_callbacks const * clbk, void * user, int * x, int * y, int * comp, int req_comp)
Definition at line 280 of file stb_image.cpp.
 {
    stbi s;
    start_callbacks(&s, (stbi_io_callbacks *) clbk, user);
    return stbi_loadf_main(&s,x,y,comp,req_comp);
 }
float* stbi_loadf_from_file (FILE * f, int * x, int * y, int * comp, int req_comp)
Definition at line 298 of file stb_image.cpp.
Referenced by stbi_loadf().
 {
    stbi s;
    start_file(&s,f);
    return stbi_loadf_main(&s,x,y,comp,req_comp);
 }
float* stbi_loadf_from_memory (stbi_uc const * buffer, int len, int * x, int * y, int * comp, int req_comp)
Definition at line 273 of file stb_image.cpp.
 {
    stbi s;
    start_mem(&s,buffer,len);
    return stbi_loadf_main(&s,x,y,comp,req_comp);
 }
void stbi_set_unpremultiply_on_load (int flag_true_if_should_unpremultiply)
Definition at line 2294 of file stb_image.cpp.
 {
    stbi_unpremultiply_on_load = flag_true_if_should_unpremultiply;
 }
int stbi_zlib_decode_buffer (char * obuffer, int olen, const char * ibuffer, int ilen)
Definition at line 2008 of file stb_image.cpp.
 {
    zbuf a;
    a.zbuffer = (uint8 *) ibuffer;
    a.zbuffer_end = (uint8 *) ibuffer + ilen;
    if (do_zlib(&a, obuffer, olen, 0, 1))
       return (int) (a.zout - a.zout_start);
    else
       return -1;
 }
char* stbi_zlib_decode_malloc (const char * buffer, int len, int * outlen)
Definition at line 1987 of file stb_image.cpp.
 {
    return stbi_zlib_decode_malloc_guesssize(buffer, len, 16384, outlen);
 }
char* stbi_zlib_decode_malloc_guesssize (const char * buffer, int len, int initial_size, int * outlen)
Definition at line 1971 of file stb_image.cpp.
Referenced by stbi_zlib_decode_malloc().
 {
    zbuf a;
    char *p = (char *) malloc(initial_size);
    if (p == NULL) return NULL;
    a.zbuffer = (uint8 *) buffer;
    a.zbuffer_end = (uint8 *) buffer + len;
    if (do_zlib(&a, p, initial_size, 1, 1)) {
       if (outlen) *outlen = (int) (a.zout - a.zout_start);
       return a.zout_start;
    } else {
       free(a.zout_start);
       return NULL;
    }
 }
int stbi_zlib_decode_noheader_buffer (char * obuffer, int olen, const char * ibuffer, int ilen)
Definition at line 2035 of file stb_image.cpp.
 {
    zbuf a;
    a.zbuffer = (uint8 *) ibuffer;
    a.zbuffer_end = (uint8 *) ibuffer + ilen;
    if (do_zlib(&a, obuffer, olen, 0, 0))
       return (int) (a.zout - a.zout_start);
    else
       return -1;
 }
char* stbi_zlib_decode_noheader_malloc (const char * buffer, int len, int * outlen)
Definition at line 2019 of file stb_image.cpp.
 {
    zbuf a;
    char *p = (char *) malloc(16384);
    if (p == NULL) return NULL;
    a.zbuffer = (uint8 *) buffer;
    a.zbuffer_end = (uint8 *) buffer+len;
    if (do_zlib(&a, p, 16384, 1, 0)) {
       if (outlen) *outlen = (int) (a.zout - a.zout_start);
       return a.zout_start;
    } else {
       free(a.zout_start);
       return NULL;
    }
 }