# Install script for directory: /home/istvan/Desktop/RobotEvolver/master/Bullet/bullet/Demos

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "0")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/HelloWorld/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/OpenGL/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/AllBulletDemos/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/ConvexDecompositionDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/CcdPhysicsDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/BulletXmlImportDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/ConstraintDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/SliderConstraintDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/GenericJointDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/Raytracer/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/RagdollDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/ForkLiftDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/BasicDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/FeatherstoneMultiBodyDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/RollingFrictionDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/RaytestDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/VoronoiFractureDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/GyroscopicDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/FractureDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/Box2dDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/BspDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/MovingConcaveDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/VehicleDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/UserCollisionAlgorithm/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/CharacterDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/SoftDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/CollisionInterfaceDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/ConcaveConvexcastDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/SimplexDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/DynamicControlDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/ConvexHullDistance/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/DoublePrecisionDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/ConcaveDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/CollisionDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/ContinuousConvexCollision/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/ConcaveRaycastDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/GjkConvexCastDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/MultiMaterialDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/SerializeDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/InternalEdgeDemo/cmake_install.cmake")
  include("/home/istvan/Desktop/RobotEvolver/master/Bullet/BuildNative/Demos/Benchmarks/cmake_install.cmake")

endif()

