RobotEvolver: MeshTools Class Reference
MeshTools Class Reference
Mesh generation and modification tools.
#include <MeshTools.h>
Public Member Functions
MeshTools ()
~MeshTools ()
std::vector< float > getVertices ()
std::vector< std::array< int, 3 > > getFaces ()
MeshT ctor_cube ()
MeshT subdivide (int divisions)
Make this mesh a cube.
Private Attributes
MeshT mesh
Detailed Description
Mesh generation and modification tools.
Definition at line 20 of file MeshTools.h.
Constructor & Destructor Documentation
MeshTools::MeshTools () inline
Definition at line 25 of file MeshTools.h.
 {MeshT mesh;};
MeshTools::~MeshTools () inline
Definition at line 26 of file MeshTools.h.
 {};
Member Function Documentation
MeshT MeshTools::ctor_cube ()
Definition at line 43 of file MeshTools.cpp.
Referenced by OpenMeshCube().
 {
   // generate vertices
   MeshT::VertexHandle vhandle[8];
   vhandle[0] = mesh.add_vertex(MeshT::Point(-1, -1,  1));
   vhandle[1] = mesh.add_vertex(MeshT::Point( 1, -1,  1));
   vhandle[2] = mesh.add_vertex(MeshT::Point( 1,  1,  1));
   vhandle[3] = mesh.add_vertex(MeshT::Point(-1,  1,  1));
   vhandle[4] = mesh.add_vertex(MeshT::Point(-1, -1, -1));
   vhandle[5] = mesh.add_vertex(MeshT::Point( 1, -1, -1));
   vhandle[6] = mesh.add_vertex(MeshT::Point( 1,  1, -1));
   vhandle[7] = mesh.add_vertex(MeshT::Point(-1,  1, -1));
   // generate (quadrilateral) faces
   std::vector<MeshT::VertexHandle> face_vhandles;
   face_vhandles.clear();
   face_vhandles.push_back(vhandle[0]);
   face_vhandles.push_back(vhandle[1]);
   face_vhandles.push_back(vhandle[2]);
   face_vhandles.push_back(vhandle[3]);
   mesh.add_face(face_vhandles);
   face_vhandles.clear();
   face_vhandles.push_back(vhandle[7]);
   face_vhandles.push_back(vhandle[6]);
   face_vhandles.push_back(vhandle[5]);
   face_vhandles.push_back(vhandle[4]);
   mesh.add_face(face_vhandles);
   face_vhandles.clear();
   face_vhandles.push_back(vhandle[1]);
   face_vhandles.push_back(vhandle[0]);
   face_vhandles.push_back(vhandle[4]);
   face_vhandles.push_back(vhandle[5]);
   mesh.add_face(face_vhandles);
   face_vhandles.clear();
   face_vhandles.push_back(vhandle[2]);
   face_vhandles.push_back(vhandle[1]);
   face_vhandles.push_back(vhandle[5]);
   face_vhandles.push_back(vhandle[6]);
   mesh.add_face(face_vhandles);
   face_vhandles.clear();
   face_vhandles.push_back(vhandle[3]);
   face_vhandles.push_back(vhandle[2]);
   face_vhandles.push_back(vhandle[6]);
   face_vhandles.push_back(vhandle[7]);
   mesh.add_face(face_vhandles);
   face_vhandles.clear();
   face_vhandles.push_back(vhandle[0]);
   face_vhandles.push_back(vhandle[3]);
   face_vhandles.push_back(vhandle[7]);
   face_vhandles.push_back(vhandle[4]);
   mesh.add_face(face_vhandles);
   return mesh;
 }
std::vector< std::array< int, 3 > > MeshTools::getFaces ()
Definition at line 17 of file MeshTools.cpp.
Referenced by OpenMeshCube().
 {
   std::vector<std::array<int, 3>> faces;
   // iterate over all faces
   for (MeshT::FaceIter f_it = mesh.faces_sbegin(); f_it != mesh.faces_end(); ++f_it)
     {
       // Get the face-vertex circulator of face _fh
       MeshT::FaceVertexIter fv_it=mesh.fv_iter (*f_it);
       //place to store the verts
       std::array<int, 3> verts;
       for(int i=0; i < 3; i++)
         {
           fv_it++;
           verts[i] = fv_it->idx();
         }
       //store the face in the vector
       faces.push_back(verts);
     }
   return faces;
 }
std::vector< float > MeshTools::getVertices ()
Definition at line 3 of file MeshTools.cpp.
Referenced by OpenMeshCube().
 {
   std::vector<float> verts;
   for (MeshT::VertexIter v_it = mesh.vertices_sbegin(); v_it != mesh.vertices_end(); ++v_it)
     {
       verts.push_back(mesh.point(*v_it)[0]);
       verts.push_back(mesh.point(*v_it)[1]);
       verts.push_back(mesh.point(*v_it)[2]);
     }
   return verts;
 }
MeshT MeshTools::subdivide (int divisions)
Make this mesh a cube.
Definition at line 104 of file MeshTools.cpp.
Referenced by OpenMeshCube().
 {
   // Initialize subdivider
   OpenMesh::Subdivider::Uniform::Sqrt3T<MeshT> subdivider;
   // Execute subdivision
   subdivider.attach(mesh);
   subdivider( divisions );
   subdivider.detach();
   return mesh;
 }
Field Documentation
MeshT MeshTools::mesh private
Definition at line 22 of file MeshTools.h.
Referenced by ctor_cube(), getFaces(), getVertices(), MeshTools(), and subdivide().
The documentation for this class was generated from the following files:
MeshTools.h
MeshTools.cpp