RobotEvolver: GL_DialogWindow.cpp File Reference
GL_DialogWindow.cpp File Reference
#include "GL_DialogWindow.h"
#include "GLDebugFont.h"
#include "btBulletDynamicsCommon.h"
#include <stdio.h>
Macros
#define USE_ARRAYS 1
Functions
static void drawLine (int _X0, int _Y0, int _X1, int _Y1, unsigned int _Color0, unsigned int _Color1)
static void drawRect (int horStart, int vertStart, int horEnd, int vertEnd, unsigned int argbColor00, unsigned int argbColor10, unsigned int argbColor01, unsigned int argbColor11)
Macro Definition Documentation
#define USE_ARRAYS 1
Definition at line 25 of file GL_DialogWindow.cpp.
Function Documentation
static void drawLine (int _X0, int _Y0, int _X1, int _Y1, unsigned int _Color0, unsigned int _Color1) static
Definition at line 54 of file GL_DialogWindow.cpp.
Referenced by GL_DialogWindow::draw().
 {
     const GLfloat dx = +0.5f;
     const GLfloat dy = -0.5f;
     GLfloat vVertices[] = {(GLfloat)_X0+dx,(GLfloat)_Y0+dy,(GLfloat)_X1+dx,(GLfloat)_Y1+dy};
     bool antiAliased = false;
     if( antiAliased )
         glEnable(GL_LINE_SMOOTH);
     else
         glDisable(GL_LINE_SMOOTH);
     glDisable(GL_TEXTURE_2D);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
 #ifdef USE_ARRAYS
     glColor4ub(GLubyte(_Color0>>16), GLubyte(_Color0>>8), GLubyte(_Color0), GLubyte(_Color0>>24));
     glDisableClientState(GL_COLOR_ARRAY);
     glDisableClientState(GL_NORMAL_ARRAY);
     glDisableClientState(GL_TEXTURE_COORD_ARRAY);
     glLineWidth(2.0f);
     glVertexPointer(2, GL_FLOAT, 0, vVertices);
     glEnableClientState(GL_VERTEX_ARRAY);
     glDrawArrays(GL_LINES,0,2);
 #else
     glLineWidth(13.0f);
     glBegin(GL_LINES);
         glColor4ub(GLubyte(_Color0>>16), GLubyte(_Color0>>8), GLubyte(_Color0), GLubyte(_Color0>>24));
         glVertex2f((GLfloat)_X0+dx, (GLfloat)_Y0+dy);
         glColor4ub(GLubyte(_Color1>>16), GLubyte(_Color1>>8), GLubyte(_Color1), GLubyte(_Color1>>24));
         glVertex2f((GLfloat)_X1+dx, (GLfloat)_Y1+dy);
     glEnd();
 #endif
     glDisable(GL_LINE_SMOOTH);
 }
static void drawRect (int horStart, int vertStart, int horEnd, int vertEnd, unsigned int argbColor00, unsigned int argbColor10, unsigned int argbColor01, unsigned int argbColor11) static
Definition at line 91 of file GL_DialogWindow.cpp.
Referenced by GL_ToggleControl::draw(), GL_SliderControl::draw(), and GL_DialogWindow::draw().
 {
     float dx = 0;
     float dy = 0;
     glDisable(GL_TEXTURE_2D);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
 #ifdef USE_ARRAYS
     GLfloat verts[] ={
             0.0f, 1.0f, 0.0f,
             -1.0f, -1.0f, 0.0f,
             1.0f, -1.0f, 0.0f,
             0.f,0.f,0.f
         };
      glColor4ub(GLubyte(argbColor00>>16), GLubyte(argbColor00>>8), GLubyte(argbColor00), GLubyte(argbColor00>>24));
     verts[0] = (GLfloat)horStart+dx;        verts[1] = (GLfloat)vertStart+dy;
     verts[2] = (GLfloat)horEnd+dx;          verts[3] = (GLfloat)vertStart+dy;
     verts[4] = (GLfloat)horEnd+dx;          verts[5] = (GLfloat)vertEnd+dy;
     verts[6] = (GLfloat)horStart+dx;        verts[7] = (GLfloat)vertEnd+dy;
     glDisableClientState(GL_COLOR_ARRAY);
     glDisableClientState(GL_NORMAL_ARRAY);
     glDisableClientState (GL_TEXTURE_COORD_ARRAY);
     glEnableClientState(GL_VERTEX_ARRAY);
     glVertexPointer(2, GL_FLOAT, 0, verts);
     glDrawArrays(GL_TRIANGLE_FAN, 0, 4);
 #else
     glBegin(GL_QUADS);
          glColor4ub(GLubyte(argbColor00>>16), GLubyte(argbColor00>>8), GLubyte(argbColor00), GLubyte(argbColor00>>24));
         glVertex2f((GLfloat)horStart+dx, (GLfloat)vertStart+dy);
         glColor4ub(GLubyte(argbColor10>>16), GLubyte(argbColor10>>8), GLubyte(argbColor10), GLubyte(argbColor10>>24));
         glVertex2f((GLfloat)horEnd+dx, (GLfloat)vertStart+dy);
         glColor4ub(GLubyte(argbColor11>>16), GLubyte(argbColor11>>8), GLubyte(argbColor11), GLubyte(argbColor11>>24));
         glVertex2f((GLfloat)horEnd+dx, (GLfloat)vertEnd+dy);
         glColor4ub(GLubyte(argbColor01>>16), GLubyte(argbColor01>>8), GLubyte(argbColor01), GLubyte(argbColor01>>24));
         glVertex2f((GLfloat)horStart+dx, (GLfloat)vertEnd+dy);
     glEnd();
 #endif
 }