RobotEvolver: GlutStuff.cpp File Reference
GlutStuff.cpp File Reference
#include "DemoApplication.h"
#include "GlutStuff.h"
Functions
static void glutKeyboardCallback (unsigned char key, int x, int y)
static void glutKeyboardUpCallback (unsigned char key, int x, int y)
static void glutSpecialKeyboardCallback (int key, int x, int y)
static void glutSpecialKeyboardUpCallback (int key, int x, int y)
static void glutReshapeCallback (int w, int h)
static void glutMoveAndDisplayCallback ()
static void glutMouseFuncCallback (int button, int state, int x, int y)
static void glutMotionFuncCallback (int x, int y)
static void glutDisplayCallback (void)
int glutmain (int argc, char **argv, int width, int height, const char *title, DemoApplication *demoApp)
Variables
static DemoApplication * gDemoApplication = 0
Function Documentation
static void glutDisplayCallback (void) static
Definition at line 69 of file GlutStuff.cpp.
Referenced by glutmain().
 {
     gDemoApplication->displayCallback();
 }
static void glutKeyboardCallback (unsigned char key, int x, int y) static
Definition at line 26 of file GlutStuff.cpp.
Referenced by glutmain().
 {
     gDemoApplication->keyboardCallback(key,x,y);
 }
static void glutKeyboardUpCallback (unsigned char key, int x, int y) static
Definition at line 31 of file GlutStuff.cpp.
Referenced by glutmain().
 {
   gDemoApplication->keyboardUpCallback(key,x,y);
 }
int glutmain (int argc, char ** argv, int width, int height, const char * title, DemoApplication * demoApp)
Definition at line 75 of file GlutStuff.cpp.
Referenced by main().
{
     gDemoApplication = demoApp;
     glutInit(&argc, argv);
     glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA | GLUT_DEPTH | GLUT_STENCIL);
     glutInitWindowPosition(width/2, height/2);
     glutInitWindowSize(width, height);
     glutCreateWindow(title);
 #ifdef BT_USE_FREEGLUT
     glutSetOption (GLUT_ACTION_ON_WINDOW_CLOSE, GLUT_ACTION_GLUTMAINLOOP_RETURNS);
 #endif
     gDemoApplication->myinit();
     glutKeyboardFunc(glutKeyboardCallback);
     glutKeyboardUpFunc(glutKeyboardUpCallback);
     glutSpecialFunc(glutSpecialKeyboardCallback);
     glutSpecialUpFunc(glutSpecialKeyboardUpCallback);
     glutReshapeFunc(glutReshapeCallback);
     //createMenu();
     glutIdleFunc(glutMoveAndDisplayCallback);
     glutMouseFunc(glutMouseFuncCallback);
     glutPassiveMotionFunc(glutMotionFuncCallback);
     glutMotionFunc(glutMotionFuncCallback);
     glutDisplayFunc( glutDisplayCallback );
     glutMoveAndDisplayCallback();
 //enable vsync to avoid tearing on Apple (todo: for Windows)
 #if defined(__APPLE__) && !defined (VMDMESA)
 int swap_interval = 1;
 CGLContextObj cgl_context = CGLGetCurrentContext();
 CGLSetParameter(cgl_context, kCGLCPSwapInterval, &swap_interval);
 #endif
     glutMainLoop();
     return 0;
 }
static void glutMotionFuncCallback (int x, int y) static
Definition at line 63 of file GlutStuff.cpp.
Referenced by glutmain().
 {
     gDemoApplication->mouseMotionFunc(x,y);
 }
static void glutMouseFuncCallback (int button, int state, int x, int y) static
Definition at line 57 of file GlutStuff.cpp.
Referenced by glutmain().
 {
     gDemoApplication->mouseFunc(button,state,x,y);
 }
static void glutMoveAndDisplayCallback () static
Definition at line 52 of file GlutStuff.cpp.
Referenced by glutmain().
 {
     gDemoApplication->moveAndDisplay();
 }
static void glutReshapeCallback (int w, int h) static
Definition at line 47 of file GlutStuff.cpp.
Referenced by glutmain().
 {
     gDemoApplication->reshape(w,h);
 }
static void glutSpecialKeyboardCallback (int key, int x, int y) static
Definition at line 36 of file GlutStuff.cpp.
Referenced by glutmain().
 {
     gDemoApplication->specialKeyboard(key,x,y);
 }
static void glutSpecialKeyboardUpCallback (int key, int x, int y) static
Definition at line 41 of file GlutStuff.cpp.
Referenced by glutmain().
 {
     gDemoApplication->specialKeyboardUp(key,x,y);
 }
Variable Documentation
DemoApplication* gDemoApplication = 0 static
Definition at line 21 of file GlutStuff.cpp.